/**
 * Tenant-scoped repository for `invitation` rows.
 *
 * Design references:
 * - design.md → Components and Interfaces → Team_Service (Invitation)
 * - design.md → Data Models → Skema PostgreSQL: `invitation` table.
 *
 * Conventions:
 * - All queries are parameterized; the `email` column is `citext`, so
 *   equality comparisons are already case-insensitive at the SQL layer
 *   (no `LOWER(...)` wrappers required).
 * - Token plaintext is persisted as-is — it is a high-entropy random
 *   value generated by `Team_Service.invite` (Task 5.1), not user input.
 * - The domain `Invitation` type intentionally does NOT expose `token`;
 *   tokens are only addressable via `findByToken` for the
 *   `acceptInvitation` flow (Task 5.3).
 */

import type { Invitation, Role } from '@leads-generator/shared';

import { query, type DbExecutor } from '../repository/types.js';

/**
 * Row shape returned by `SELECT … FROM invitation`.
 *
 * `created_at` / `expires_at` may arrive as `Date` (from `pg`) or as ISO
 * strings (e.g. when a row round-trips through JSON in a test fake).
 */
export interface InvitationRow {
  id: string;
  team_id: string;
  email: string;
  role: Role;
  status: 'pending' | 'active' | 'expired';
  token: string;
  created_at: Date | string;
  expires_at: Date | string;
}

/**
 * Columns selected for the public-facing {@link Invitation} domain type.
 *
 * `token` is part of the row shape but is never propagated into the
 * domain object — it is reachable only through {@link InvitationRepository.findByToken}.
 */
const INVITATION_COLUMNS = `
  id,
  team_id,
  email,
  role,
  status,
  token,
  created_at,
  expires_at
`;

/** Coerce a `Date | string` cell into a `Date`. */
function toDate(value: Date | string): Date {
  return value instanceof Date ? value : new Date(value);
}

/** Map a row to the domain {@link Invitation} (omits `token`). */
function mapInvitationRow(row: InvitationRow): Invitation {
  return {
    id: row.id,
    teamId: row.team_id,
    email: row.email,
    role: row.role,
    status: row.status,
    createdAt: toDate(row.created_at),
    expiresAt: toDate(row.expires_at),
  };
}

/**
 * Repository for the `invitation` table. All methods are team-scoped
 * except {@link findByToken}, which is keyed by the globally-unique
 * `token` column (used by the accept-invitation flow before the caller
 * is associated with a Team).
 */
export class InvitationRepository {
  constructor(private readonly db: DbExecutor) {}

  /**
   * Insert a new `pending` invitation for the given Team + email.
   *
   * Caller responsibilities (Team_Service.invite, Task 5.1):
   * - Validate `email` shape and length (≤ 254 chars).
   * - Verify no active/pending membership or invitation already exists
   *   for this `(teamId, email)`.
   * - Provide a high-entropy `token` (base64url-encoded 32-byte random)
   *   and `expiresAt = now() + 168h` per R2.1.
   */
  async insert(input: {
    teamId: string;
    email: string;
    role: Role;
    token: string;
    expiresAt: Date;
  }): Promise<Invitation> {
    const rows = await query<InvitationRow>(
      this.db,
      `INSERT INTO invitation (
         team_id, email, role, status, token, expires_at
       ) VALUES (
         $1, $2, $3, 'pending', $4, $5
       )
       RETURNING ${INVITATION_COLUMNS}`,
      [input.teamId, input.email, input.role, input.token, input.expiresAt],
    );
    return mapInvitationRow(rows[0]!);
  }

  /**
   * Look up an invitation by its globally-unique `token`. Returns `null`
   * when the token is unknown.
   */
  async findByToken(token: string): Promise<Invitation | null> {
    const rows = await query<InvitationRow>(
      this.db,
      `SELECT ${INVITATION_COLUMNS}
         FROM invitation
        WHERE token = $1`,
      [token],
    );
    if (rows.length === 0) return null;
    return mapInvitationRow(rows[0]!);
  }

  /**
   * Find the most recent `pending` or `active` invitation for the given
   * Team + email pair. Used by `Team_Service.invite` to enforce the R2.9
   * "no duplicate active/pending invitation" rule.
   *
   * Returns `null` when no such invitation exists. Email comparison is
   * case-insensitive at the SQL layer because the `email` column is
   * declared `citext`.
   */
  async findActiveOrPendingByEmail(teamId: string, email: string): Promise<Invitation | null> {
    const rows = await query<InvitationRow>(
      this.db,
      `SELECT ${INVITATION_COLUMNS}
         FROM invitation
        WHERE team_id = $1
          AND email = $2
          AND status IN ('pending','active')
        ORDER BY created_at DESC
        LIMIT 1`,
      [teamId, email],
    );
    if (rows.length === 0) return null;
    return mapInvitationRow(rows[0]!);
  }

  /** Update the lifecycle `status` of an invitation by id. */
  async setStatus(id: string, status: 'pending' | 'active' | 'expired'): Promise<void> {
    await query(
      this.db,
      `UPDATE invitation
          SET status = $2
        WHERE id = $1`,
      [id, status],
    );
  }
}
