// Local type alias for layout variant IDs (string-based)
type LayoutVariantId = string;

export interface NarrativeArcPreset {
  id: string;
  name: string;
  triggers: string[];
  bestFor: string;
  slideRoles: Array<{
    role: string;
    narrativeGoal: string;
    layoutCandidates: LayoutVariantId[];
    componentMix: string[];
    imageUse: 'required' | 'optional' | 'none';
  }>;
}

export interface ImageStylePreset {
  id: string;
  name: string;
  triggers: string[];
  promptFragment: string;
  avoid: string[];
  bestFor: string[];
  providerStyle?: {
    imaginer?: Record<string, string>;
  };
}

export interface LayoutRecipePreset {
  id: string;
  name: string;
  triggers: string[];
  useWhen: string;
  layoutCandidates: LayoutVariantId[];
  componentMix: string[];
  narrativeRole: string;
}

const NARRATIVE_ARCS: NarrativeArcPreset[] = [
  {
    id: 'problem_cost_solution',
    name: 'Problem, Cost, Solution',
    triggers: ['problem', 'masalah', 'kenapa', 'kehilangan', 'lambat', 'pain', 'solusi'],
    bestFor:
      'Education plus soft selling where the user wants to expose a pain and offer a better way.',
    slideRoles: [
      {
        role: 'hook',
        narrativeGoal: 'Name the painful problem in one sharp statement.',
        layoutCandidates: ['cover_editorial_left', 'cover_centered', 'cover_with_cta'],
        componentMix: ['tag', 'header', 'body'],
        imageUse: 'none',
      },
      {
        role: 'visible_cost',
        narrativeGoal: 'Show what the problem quietly costs the audience.',
        layoutCandidates: ['split_image_left_text_right', 'split_stat_image', 'stat_highlight'],
        componentMix: ['header', 'body', 'image_placeholder or stat'],
        imageUse: 'optional',
      },
      {
        role: 'why_it_happens',
        narrativeGoal: 'Explain the mechanism behind the problem.',
        layoutCandidates: [
          'feature_cards_with_header',
          'checklist_with_body',
          'comparison_with_header',
        ],
        componentMix: ['header', 'feature_cards or checklist or comparison'],
        imageUse: 'none',
      },
      {
        role: 'better_way',
        narrativeGoal: 'Present the recommended behavior, system, or product angle.',
        layoutCandidates: ['numbered_steps', 'numbered_with_image', 'split_header_body_cta'],
        componentMix: ['header', 'checklist', 'button_cta optional'],
        imageUse: 'optional',
      },
      {
        role: 'cta',
        narrativeGoal: 'Close with a concrete next action.',
        layoutCandidates: ['header_body_cta', 'cta_centered', 'quote_stat_combo'],
        componentMix: ['header', 'body or quote', 'button_cta'],
        imageUse: 'none',
      },
    ],
  },
  {
    id: 'warning_prevention_playbook',
    name: 'Warning and Prevention Playbook',
    triggers: [
      'bahaya',
      'risiko',
      'warning',
      'pencegahan',
      'preventif',
      'efektif',
      'dampak',
      'rumah tangga',
    ],
    bestFor: 'Sensitive education, mental health, family, safety, and risk-awareness content.',
    slideRoles: [
      {
        role: 'empathetic_hook',
        narrativeGoal: 'Open with a non-judgmental warning that feels human, not sensational.',
        layoutCandidates: ['cover_editorial_left', 'cover_checklist', 'cover_centered'],
        componentMix: ['tag', 'header', 'body or checklist'],
        imageUse: 'none',
      },
      {
        role: 'symbolic_impact',
        narrativeGoal: 'Use one symbolic visual metaphor to make the hidden impact concrete.',
        layoutCandidates: [
          'split_image_left_text_right',
          'image_top_text_bottom',
          'quote_with_image',
        ],
        componentMix: ['image_placeholder', 'header', 'body or quote'],
        imageUse: 'required',
      },
      {
        role: 'symptoms_or_signals',
        narrativeGoal: 'List early warning signs the audience can recognize.',
        layoutCandidates: ['feature_cards_with_header', 'checklist_with_body', 'two_column_text'],
        componentMix: ['header', 'feature_cards or checklist'],
        imageUse: 'none',
      },
      {
        role: 'prevention_protocol',
        narrativeGoal: 'Turn advice into a step-by-step prevention plan.',
        layoutCandidates: ['numbered_steps', 'image_top_checklist_bottom', 'numbered_with_image'],
        componentMix: ['header', 'checklist', 'image_placeholder optional'],
        imageUse: 'optional',
      },
      {
        role: 'supportive_close',
        narrativeGoal:
          'Close with a calm invitation to talk, seek help, or take one safe next step.',
        layoutCandidates: ['header_body_cta', 'quote_focus', 'cta_centered'],
        componentMix: ['quote or header', 'body optional', 'button_cta optional'],
        imageUse: 'none',
      },
    ],
  },
  {
    id: 'before_after_bridge',
    name: 'Before, After, Bridge',
    triggers: [
      'sebelum',
      'sesudah',
      'before',
      'after',
      'transformasi',
      'dulu',
      'sekarang',
      'manual',
      'otomatis',
    ],
    bestFor: 'Transformation stories, process improvement, and product positioning.',
    slideRoles: [
      {
        role: 'before_state',
        narrativeGoal: 'Show the old frustrating state.',
        layoutCandidates: ['cover_editorial_left', 'comparison_with_header'],
        componentMix: ['header', 'body or comparison'],
        imageUse: 'none',
      },
      {
        role: 'after_state',
        narrativeGoal: 'Show what changes when the audience adopts the better way.',
        layoutCandidates: ['comparison_columns', 'feature_cards_with_header'],
        componentMix: ['comparison or feature_cards'],
        imageUse: 'none',
      },
      {
        role: 'bridge_steps',
        narrativeGoal: 'Explain the transition in clear steps.',
        layoutCandidates: ['numbered_steps', 'numbered_with_image'],
        componentMix: ['header', 'checklist', 'image_placeholder optional'],
        imageUse: 'optional',
      },
      {
        role: 'proof',
        narrativeGoal: 'Add proof, metric, or concrete example.',
        layoutCandidates: ['stat_highlight', 'split_stat_image', 'quote_stat_combo'],
        componentMix: ['header', 'body or quote', 'image_placeholder optional'],
        imageUse: 'optional',
      },
      {
        role: 'action',
        narrativeGoal: 'Ask the audience to try the new behavior.',
        layoutCandidates: ['header_body_cta', 'cta_centered'],
        componentMix: ['header', 'body', 'button_cta'],
        imageUse: 'none',
      },
    ],
  },
  {
    id: 'myth_truth_reframe',
    name: 'Myth, Truth, Reframe',
    triggers: ['mitos', 'myth', 'salah kaprah', 'fakta', 'truth', 'reframe', 'keliru'],
    bestFor: 'Educational content that corrects misconceptions.',
    slideRoles: [
      {
        role: 'myth_hook',
        narrativeGoal: 'State the misconception in a provocative but clear way.',
        layoutCandidates: ['cover_editorial_left', 'big_statement'],
        componentMix: ['tag', 'header'],
        imageUse: 'none',
      },
      {
        role: 'truth',
        narrativeGoal: 'Explain the truth with a short rationale.',
        layoutCandidates: ['text_stack', 'quote_stat_combo', 'stat_highlight'],
        componentMix: ['header', 'body or quote'],
        imageUse: 'none',
      },
      {
        role: 'evidence',
        narrativeGoal: 'Show signs, examples, or proof points.',
        layoutCandidates: ['feature_cards_with_header', 'split_checklist_image'],
        componentMix: ['feature_cards or checklist', 'image_placeholder optional'],
        imageUse: 'optional',
      },
      {
        role: 'new_frame',
        narrativeGoal: 'Give the audience a better mental model.',
        layoutCandidates: ['comparison_with_header', 'two_column_text'],
        componentMix: ['comparison or checklist'],
        imageUse: 'none',
      },
      {
        role: 'practice',
        narrativeGoal: 'Turn the reframe into one practical action.',
        layoutCandidates: ['numbered_steps', 'header_body_cta'],
        componentMix: ['header', 'checklist or button_cta'],
        imageUse: 'none',
      },
    ],
  },
  {
    id: 'product_demo_value',
    name: 'Product Demo Value Story',
    triggers: [
      'produk',
      'product',
      'fitur',
      'feature',
      'saas',
      'dashboard',
      'demo',
      'soft selling',
    ],
    bestFor: 'Product-led education and soft selling.',
    slideRoles: [
      {
        role: 'category_hook',
        narrativeGoal: 'Name the category pain or opportunity.',
        layoutCandidates: ['cover_editorial_left', 'cover_with_cta'],
        componentMix: ['tag', 'header', 'body optional'],
        imageUse: 'none',
      },
      {
        role: 'use_case_visual',
        narrativeGoal: 'Show the product or use case visually.',
        layoutCandidates: [
          'split_image_left_text_right',
          'image_full_caption',
          'split_header_body_cta',
        ],
        componentMix: ['image_placeholder', 'header', 'body or button_cta'],
        imageUse: 'required',
      },
      {
        role: 'value_cards',
        narrativeGoal: 'Break the value into concrete benefit cards.',
        layoutCandidates: ['feature_cards_with_header', 'feature_cards_grid'],
        componentMix: ['header optional', 'feature_cards'],
        imageUse: 'none',
      },
      {
        role: 'workflow',
        narrativeGoal: 'Show how the audience would use it.',
        layoutCandidates: ['numbered_steps', 'numbered_with_image'],
        componentMix: ['header', 'checklist', 'image_placeholder optional'],
        imageUse: 'optional',
      },
      {
        role: 'conversion_close',
        narrativeGoal: 'Close with the product promise and next action.',
        layoutCandidates: ['header_body_cta', 'split_header_body_cta', 'cta_centered'],
        componentMix: ['header', 'body', 'button_cta', 'image_placeholder optional'],
        imageUse: 'optional',
      },
    ],
  },
];

const IMAGE_STYLES: ImageStylePreset[] = [
  {
    id: 'doodle_handdrawn',
    name: 'Hand-drawn Doodle',
    triggers: ['doodle', 'hand drawn', 'hand-drawn', 'sketch', 'line art', 'gambar tangan'],
    promptFragment:
      'true hand-drawn doodle, loose black ink sketch lines, simple playful shapes, minimal flat color accents, white or transparent-feeling negative space',
    avoid: [
      'photorealistic',
      '3D render',
      'stock photo',
      'polished corporate vector art',
      'generic editorial illustration',
    ],
    bestFor: ['education', 'sensitive topics', 'casual explainer', 'metaphor visual'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'modern_saas_ui',
    name: 'Modern SaaS UI Mockup',
    triggers: ['saas', 'dashboard', 'ui mockup', 'floating cards', 'connector lines', 'modern'],
    promptFragment:
      'modern SaaS UI mockup, clean dashboard panels, floating cards, connector lines, subtle depth, crisp product-like interface details',
    avoid: [
      'stock office photo',
      'messy interface',
      'illegible text',
      'overly decorative hero art',
    ],
    bestFor: ['software product', 'lead generation', 'workflow explanation', 'B2B education'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'flat_vector',
    name: 'Flat Vector Explainer',
    triggers: ['flat vector', 'vector', 'flat illustration', 'minimal vector'],
    promptFragment:
      'flat vector explainer illustration, clean geometric forms, consistent stroke weight, minimal shading, brand-friendly shapes',
    avoid: ['photorealistic', '3D', 'busy texture', 'stock photo'],
    bestFor: ['education', 'process', 'feature cards', 'comparison'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'editorial_photo',
    name: 'Editorial Photo',
    triggers: ['photo', 'foto', 'photorealistic', 'realistic', 'editorial'],
    promptFragment:
      'editorial realistic photo style, natural light, believable materials, intentional composition, non-stock candid framing',
    avoid: ['cartoon', 'flat vector', 'overly staged stock photo', 'fake text'],
    bestFor: ['product', 'lifestyle', 'human context', 'premium brand'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'watercolor_soft',
    name: 'Soft Watercolor',
    triggers: ['watercolor', 'aquarel', 'soft painting', 'painted'],
    promptFragment:
      'soft watercolor illustration, gentle washes, organic edges, airy composition, calm handcrafted texture',
    avoid: ['hard vector edges', '3D render', 'photorealistic', 'neon colors'],
    bestFor: ['wellness', 'family', 'emotional education', 'gentle storytelling'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'sticker_cutout',
    name: 'Sticker Cutout',
    triggers: [
      'sticker',
      'cutout',
      'transparent',
      'transparan',
      'no background',
      'tanpa background',
    ],
    promptFragment:
      'clean sticker cutout, isolated subject, crisp silhouette, generous padding, transparent or plain background composition',
    avoid: ['full scene background', 'busy environment', 'cast shadow covering text area'],
    bestFor: ['carousel objects', 'icons', 'small supporting visuals', 'product cutouts'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'isometric_3d',
    name: 'Isometric 3D',
    triggers: ['isometric', '3d', 'soft 3d', 'clay'],
    promptFragment:
      'clean isometric 3D illustration, soft lighting, simple shapes, controlled perspective, polished but not cluttered',
    avoid: ['photorealistic chaos', 'busy background', 'illegible text'],
    bestFor: ['systems', 'workflow', 'product concept', 'process map'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'anime',
    name: 'Anime Style',
    triggers: ['anime', 'manga'],
    promptFragment:
      'anime-inspired illustration, expressive character design, clean linework, cinematic framing, controlled detail',
    avoid: ['photorealistic', 'western corporate vector', 'messy anatomy'],
    bestFor: ['entertainment', 'youthful education', 'story-driven content'],
    providerStyle: { imaginer: { 'nano-banana-2': 'anime' } },
  },
  {
    id: 'product_photo_premium',
    name: 'Premium Product Photo',
    triggers: ['product photo', 'foto produk', 'produk premium', 'catalog', 'katalog', 'packshot'],
    promptFragment:
      'premium product photography, clean studio lighting, crisp material detail, intentional shadows, catalog-quality composition',
    avoid: ['cartoon', 'messy background', 'fake labels', 'cheap stock-photo look'],
    bestFor: ['product launch', 'catalog visual', 'ecommerce', 'premium offer'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'lifestyle_photo',
    name: 'Lifestyle Photo',
    triggers: [
      'lifestyle',
      'aktivitas',
      'sehari-hari',
      'real life',
      'orang menggunakan',
      'customer using',
    ],
    promptFragment:
      'natural lifestyle photography, believable everyday setting, human context, soft natural light, non-stock candid framing',
    avoid: ['posed stock photo', 'cartoon', 'overly polished ad scene', 'fake text'],
    bestFor: ['human use case', 'consumer education', 'service benefits', 'social proof'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'cinematic_photo',
    name: 'Cinematic Photo',
    triggers: ['cinematic', 'dramatic', 'film look', 'moody', 'sinematik'],
    promptFragment:
      'cinematic photo style, dramatic lighting, controlled contrast, shallow depth of field, filmic color grading',
    avoid: ['flat lighting', 'cartoon', 'generic stock photo', 'overexposed scene'],
    bestFor: ['emotional hook', 'brand storytelling', 'premium campaign', 'dramatic contrast'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'documentary_photo',
    name: 'Documentary Photo',
    triggers: ['documentary', 'reportage', 'realistic scene', 'jurnalistik', 'lapangan'],
    promptFragment:
      'documentary photography, grounded real-world scene, honest composition, available light, subtle environmental detail',
    avoid: ['staged advertisement', 'fantasy render', 'cartoon', 'glossy stock look'],
    bestFor: ['social issue', 'community story', 'public education', 'field reporting'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'luxury_editorial',
    name: 'Luxury Editorial',
    triggers: ['luxury', 'mewah', 'premium', 'elegant', 'high-end', 'eksklusif'],
    promptFragment:
      'luxury editorial visual style, refined composition, premium materials, generous negative space, sophisticated lighting',
    avoid: ['cheap gradients', 'busy clutter', 'cartoonish props', 'low-end stock look'],
    bestFor: ['premium product', 'luxury brand', 'executive audience', 'high-ticket offer'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'food_photo',
    name: 'Food Photography',
    triggers: ['food', 'makanan', 'minuman', 'restaurant', 'kuliner', 'menu'],
    promptFragment:
      'appetizing food photography, natural texture, fresh ingredients, warm directional light, clean table styling',
    avoid: ['plastic-looking food', 'messy plating', 'cartoon', 'fake text on packaging'],
    bestFor: ['restaurant', 'menu promotion', 'culinary education', 'food product'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'interior_architecture',
    name: 'Interior Architecture',
    triggers: ['interior', 'ruangan', 'arsitektur', 'home decor', 'kantor', 'cafe', 'workspace'],
    promptFragment:
      'interior architecture visual, balanced spatial composition, natural materials, realistic lighting, clean design-magazine framing',
    avoid: ['distorted perspective', 'clutter', 'cartoon', 'unrealistic furniture scale'],
    bestFor: ['property', 'workspace', 'hospitality', 'home product'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'fashion_editorial',
    name: 'Fashion Editorial',
    triggers: ['fashion', 'busana', 'outfit', 'apparel', 'model', 'lookbook'],
    promptFragment:
      'fashion editorial photography, styled outfit focus, elegant pose, refined lighting, magazine lookbook composition',
    avoid: ['awkward anatomy', 'messy clothing', 'cartoon', 'cheap catalog lighting'],
    bestFor: ['fashion brand', 'apparel launch', 'personal brand', 'lookbook'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'editorial_illustration',
    name: 'Editorial Illustration',
    triggers: [
      'editorial illustration',
      'ilustrasi editorial',
      'opini',
      'majalah',
      'conceptual illustration',
    ],
    promptFragment:
      'conceptual editorial illustration, smart visual metaphor, balanced composition, refined shapes, publication-quality art direction',
    avoid: ['generic vector people', 'stock illustration', 'photorealistic', 'overcrowded details'],
    bestFor: ['abstract topic', 'opinion content', 'education', 'thought leadership'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'comic_panel',
    name: 'Comic Panel',
    triggers: ['comic', 'komik', 'panel', 'storyboard', 'cartoon panel'],
    promptFragment:
      'comic panel illustration, expressive characters, bold linework, clear scene staging, sequential-story energy without text bubbles',
    avoid: ['photorealistic', 'messy panels', 'illegible lettering', 'overly complex background'],
    bestFor: ['storytelling', 'scenario explanation', 'youth content', 'cause-effect'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'mascot_character',
    name: 'Mascot Character',
    triggers: ['mascot', 'character', 'karakter', 'avatar', 'brand character'],
    promptFragment:
      'friendly mascot character illustration, memorable silhouette, expressive face, simple brandable shapes, clean pose',
    avoid: ['creepy expression', 'photorealistic face', 'busy costume', 'generic clipart'],
    bestFor: ['brand education', 'onboarding', 'children-friendly content', 'assistant persona'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'infographic_diagram',
    name: 'Infographic Diagram',
    triggers: ['infographic', 'infografik', 'diagram', 'flow', 'chart visual', 'framework'],
    promptFragment:
      'clean infographic-style diagram visual, structured blocks, arrows and simple icons, clear hierarchy, minimal text-free composition',
    avoid: ['tiny readable text', 'cluttered chart', 'photorealistic', 'random labels'],
    bestFor: ['framework', 'process', 'education', 'data explanation'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'educational_diagram',
    name: 'Educational Diagram',
    triggers: [
      'edukasi',
      'edukasi diagram',
      'educational diagram',
      'explain',
      'explanation visual',
      'materi belajar',
    ],
    promptFragment:
      'educational diagram illustration, simplified concept visualization, clear relationships, clean icon-like elements, classroom-friendly clarity',
    avoid: ['photorealistic', 'dense labels', 'messy arrows', 'decorative clutter'],
    bestFor: ['learning content', 'how-it-works', 'concept breakdown', 'training material'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'app_screen_mockup',
    name: 'App Screen Mockup',
    triggers: [
      'app mockup',
      'mobile app',
      'screen mockup',
      'aplikasi',
      'phone screen',
      'mobile ui',
    ],
    promptFragment:
      'clean mobile app screen mockup, realistic device frame optional, crisp UI cards, modern product interface, no readable fake text',
    avoid: ['messy UI', 'illegible tiny text', 'stock phone hand', 'overdecorated background'],
    bestFor: ['app product', 'feature launch', 'mobile workflow', 'SaaS demo'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'web_dashboard_mockup',
    name: 'Web Dashboard Mockup',
    triggers: [
      'web dashboard',
      'dashboard web',
      'analytics dashboard',
      'admin panel',
      'crm dashboard',
    ],
    promptFragment:
      'modern web dashboard mockup, clean data cards, sidebar or top nav structure, charts as abstract shapes, polished SaaS product feel',
    avoid: ['readable fake text', 'chaotic widgets', 'stock office photo', 'dated UI'],
    bestFor: ['B2B SaaS', 'analytics', 'CRM', 'admin tool', 'product proof'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'futuristic_tech',
    name: 'Futuristic Tech',
    triggers: ['futuristic', 'future', 'ai', 'teknologi', 'cyber', 'automation', 'robotic'],
    promptFragment:
      'futuristic technology visual, sleek interface elements, luminous accents, abstract data flows, controlled high-tech atmosphere',
    avoid: ['overdone sci-fi chaos', 'illegible text', 'cliche robot overload', 'messy neon'],
    bestFor: ['AI product', 'automation', 'innovation', 'tech thought leadership'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'neon_cyber',
    name: 'Neon Cyber',
    triggers: ['neon', 'cyberpunk', 'cyber', 'glow', 'dark futuristic'],
    promptFragment:
      'neon cyber visual style, dark high-contrast background, glowing accents, sharp futuristic shapes, cinematic tech mood',
    avoid: ['muddy dark image', 'unreadable clutter', 'random text', 'cheap gradient overload'],
    bestFor: ['cybersecurity', 'nightlife', 'gaming', 'high-energy tech'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'glassmorphism_ui',
    name: 'Glassmorphism UI',
    triggers: ['glassmorphism', 'glass UI', 'frosted glass', 'translucent cards'],
    promptFragment:
      'glassmorphism UI visual, translucent frosted panels, soft highlights, layered depth, clean modern interface composition',
    avoid: ['low contrast text', 'muddy blur', 'busy background', 'dated skeuomorphism'],
    bestFor: ['modern app', 'premium SaaS', 'dashboard hero', 'tech visual'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'editorial_collage',
    name: 'Editorial Collage',
    triggers: ['collage', 'editorial collage', 'montage', 'cut and paste', 'mixed media'],
    promptFragment:
      'editorial collage, layered cutout shapes, mixed media composition, tasteful overlap, magazine art direction',
    avoid: ['messy scrapbook', 'too many objects', 'random text', 'photorealistic single scene'],
    bestFor: ['abstract concepts', 'campaign story', 'social carousel', 'brand mood'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'poster_graphic',
    name: 'Poster Graphic',
    triggers: ['poster', 'campaign poster', 'bold graphic', 'key visual', 'kv'],
    promptFragment:
      'bold poster graphic style, strong central composition, high-impact shapes, campaign key visual energy, minimal or no text',
    avoid: ['small text blocks', 'weak composition', 'generic stock photo', 'overcrowded layout'],
    bestFor: ['campaign', 'announcement', 'bold hook', 'event visual'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'magazine_layout',
    name: 'Magazine Layout Visual',
    triggers: ['magazine', 'majalah', 'editorial layout', 'publication', 'spread'],
    promptFragment:
      'magazine editorial visual, refined grid composition, art-directed image crop, premium publication feel, text-free layout impression',
    avoid: ['fake readable article text', 'clutter', 'generic brochure', 'low-end template look'],
    bestFor: ['thought leadership', 'premium education', 'brand story', 'editorial carousel'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'gouache_painting',
    name: 'Gouache Painting',
    triggers: ['gouache', 'opaque watercolor', 'painted illustration', 'lukisan gouache'],
    promptFragment:
      'gouache painting illustration, opaque painterly texture, soft edges, handcrafted warmth, rich but controlled color fields',
    avoid: ['photorealistic', 'hard vector edges', '3D render', 'neon tech look'],
    bestFor: ['emotional storytelling', 'family', 'wellness', 'warm brand content'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'pencil_sketch',
    name: 'Pencil Sketch',
    triggers: ['pencil', 'pensil', 'sketsa pensil', 'graphite', 'rough sketch'],
    promptFragment:
      'pencil sketch illustration, graphite texture, visible construction lines, soft shading, handmade study-drawing feel',
    avoid: ['photorealistic photo', 'vector polish', 'neon color', '3D render'],
    bestFor: ['concept exploration', 'human emotion', 'education', 'draft-like storytelling'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'paper_cutout',
    name: 'Paper Cutout',
    triggers: ['paper cutout', 'paper craft', 'papercut', 'cut paper', 'kertas'],
    promptFragment:
      'paper cutout illustration, layered paper shapes, tactile shadows, handmade craft texture, clean playful composition',
    avoid: ['photorealistic', 'plastic 3D', 'messy collage', 'fake printed text'],
    bestFor: ['education', 'family', 'playful brand', 'simple metaphors'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'risograph_grain',
    name: 'Risograph Grain',
    triggers: ['risograph', 'riso', 'grainy', 'grain texture', 'retro print'],
    promptFragment:
      'risograph-inspired illustration, grainy print texture, limited color palette, slight registration offset, indie poster feel',
    avoid: ['glossy 3D', 'photorealistic', 'corporate stock vector', 'too many colors'],
    bestFor: ['youth culture', 'creative campaign', 'awareness content', 'bold social post'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'pastel_soft',
    name: 'Soft Pastel',
    triggers: ['pastel', 'soft color', 'calm', 'gentle', 'lembut'],
    promptFragment:
      'soft pastel illustration, gentle colors, calm atmosphere, rounded shapes, airy negative space, soothing visual tone',
    avoid: ['harsh neon', 'dark gritty contrast', 'photorealistic', 'busy texture'],
    bestFor: ['wellness', 'family', 'mental health', 'gentle education'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'oil_painting',
    name: 'Oil Painting',
    triggers: ['oil painting', 'lukisan cat minyak', 'classical painting', 'painterly'],
    promptFragment:
      'oil painting style, painterly brushwork, rich tonal depth, classical composition, expressive light and texture',
    avoid: ['flat vector', '3D render', 'cheap digital filter', 'stock photo'],
    bestFor: ['heritage brand', 'dramatic story', 'premium art direction', 'emotional metaphor'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'minimal_icon_set',
    name: 'Minimal Icon Set',
    triggers: ['icon', 'icons', 'ikon', 'icon set', 'symbol'],
    promptFragment:
      'minimal icon set style, simple geometric symbols, consistent stroke weight, clear silhouettes, monochrome or limited accents',
    avoid: ['complex illustration', 'photorealistic', 'inconsistent icon styles', 'tiny text'],
    bestFor: ['feature cards', 'checklist support', 'product categories', 'simple explanation'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'metaphor_visual',
    name: 'Metaphor Visual',
    triggers: ['metaphor', 'simbolik', 'symbolic', 'perumpamaan', 'analogi'],
    promptFragment:
      'symbolic metaphor visual, one clear central object or scene representing the idea, simple composition, emotionally readable concept',
    avoid: ['literal clutter', 'random symbols', 'overexplaining with text', 'generic stock scene'],
    bestFor: ['abstract topic', 'sensitive topic', 'thought leadership', 'hook slide'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'children_friendly',
    name: 'Children-friendly Illustration',
    triggers: ['children', 'kids', 'anak', 'keluarga anak', 'child friendly', 'playful'],
    promptFragment:
      'children-friendly illustration, warm rounded shapes, gentle expression, playful clarity, safe and approachable visual tone',
    avoid: ['scary mood', 'adult realism', 'dark gritty style', 'overly complex detail'],
    bestFor: ['family education', 'kids product', 'parenting', 'gentle awareness'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'medical_clean',
    name: 'Clean Medical Visual',
    triggers: ['medical', 'health', 'kesehatan', 'clinic', 'dokter', 'wellness medical'],
    promptFragment:
      'clean medical visual style, trustworthy clinical clarity, soft neutral lighting, simplified health-related objects, calm professional tone',
    avoid: ['graphic injury', 'fearmongering', 'fake medical text', 'cartoonish diagnosis'],
    bestFor: ['health education', 'clinic content', 'wellness guidance', 'preventive care'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'financial_corporate',
    name: 'Financial Corporate',
    triggers: ['finance', 'financial', 'keuangan', 'investasi', 'bank', 'business finance'],
    promptFragment:
      'professional financial visual, clean charts as abstract shapes, business context, trustworthy corporate composition, restrained premium palette',
    avoid: ['get-rich cliche', 'fake readable numbers', 'casino imagery', 'cartoon money pile'],
    bestFor: ['finance education', 'B2B content', 'investment explainer', 'business planning'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'nature_organic',
    name: 'Nature Organic',
    triggers: ['nature', 'natural', 'organic', 'alam', 'eco', 'sustainable', 'green'],
    promptFragment:
      'nature-inspired organic visual, natural textures, botanical forms, earthy light, calm sustainable atmosphere',
    avoid: ['artificial plastic look', 'neon tech', 'cluttered forest scene', 'fake eco labels'],
    bestFor: ['sustainability', 'wellness', 'organic product', 'calm brand story'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'real_estate_listing',
    name: 'Real Estate Listing',
    triggers: ['real estate', 'property', 'properti', 'rumah dijual', 'apartment', 'villa'],
    promptFragment:
      'real estate listing visual, bright architectural photography, clean staging, wide-angle but natural perspective, inviting space',
    avoid: ['distorted rooms', 'messy interior', 'fake signage', 'cartoon render'],
    bestFor: ['property marketing', 'interior selling points', 'hospitality', 'home services'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'travel_editorial',
    name: 'Travel Editorial',
    triggers: ['travel', 'wisata', 'destination', 'hotel', 'trip', 'liburan'],
    promptFragment:
      'travel editorial photography, sense of place, inviting atmosphere, natural light, destination-focused composition',
    avoid: ['generic postcard look', 'overprocessed HDR', 'fake text signs', 'crowded clutter'],
    bestFor: ['tourism', 'hospitality', 'destination guide', 'experience marketing'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
  {
    id: 'event_stage',
    name: 'Event Stage Visual',
    triggers: ['event', 'webinar', 'seminar', 'conference', 'workshop', 'stage'],
    promptFragment:
      'event stage visual, professional lighting, clear focal stage or speaker setup, energetic but organized atmosphere',
    avoid: ['empty generic hall', 'fake readable banners', 'messy crowd', 'cartoon look'],
    bestFor: ['event promo', 'webinar', 'conference recap', 'training program'],
    providerStyle: { imaginer: { 'gpt-image-2': 'dynamic' } },
  },
];

const LAYOUT_RECIPES: LayoutRecipePreset[] = [
  {
    id: 'symbolic_visual_split',
    name: 'Symbolic Visual Split',
    triggers: ['impact', 'dampak', 'bahaya', 'visual', 'ilustrasi', 'metaphor'],
    useWhen: 'A slide needs one strong metaphorical image plus concise explanatory copy.',
    layoutCandidates: [
      'split_image_left_text_right',
      'split_text_left_image_right',
      'quote_with_image',
    ],
    componentMix: ['image_placeholder', 'header', 'body or quote'],
    narrativeRole: 'Make an abstract idea emotionally concrete.',
  },
  {
    id: 'symptom_cards',
    name: 'Symptom or Signal Cards',
    triggers: ['tanda', 'gejala', 'signals', 'ciri', 'symptoms', 'alasan'],
    useWhen: 'The content lists several signs, reasons, symptoms, or small concepts.',
    layoutCandidates: ['feature_cards_with_header', 'feature_cards_grid'],
    componentMix: ['header optional', 'feature_cards with 3-6 items'],
    narrativeRole: 'Make multiple points scannable and less monotonous than a checklist.',
  },
  {
    id: 'two_state_comparison',
    name: 'Two-State Comparison',
    triggers: ['dulu', 'sekarang', 'tanpa', 'dengan', 'before', 'after', 'manual', 'otomatis'],
    useWhen: 'The story contrasts two states, options, behaviors, or outcomes.',
    layoutCandidates: ['comparison_with_header', 'comparison_columns'],
    componentMix: ['comparison with 2 columns'],
    narrativeRole: 'Create tension and clarity through contrast.',
  },
  {
    id: 'prevention_steps',
    name: 'Prevention Steps',
    triggers: ['pencegahan', 'langkah', 'cara', 'step', 'playbook', 'protocol'],
    useWhen: 'The user asks what to do, how to prevent, or what sequence to follow.',
    layoutCandidates: ['numbered_steps', 'checklist_with_body', 'numbered_with_image'],
    componentMix: ['header', 'body optional', 'checklist with ordered steps'],
    narrativeRole: 'Turn advice into practical action.',
  },
  {
    id: 'proof_or_stat',
    name: 'Proof or Stat Moment',
    triggers: ['data', 'angka', 'statistik', 'proof', 'bukti', 'hasil'],
    useWhen: 'A claim needs a memorable proof point or metric.',
    layoutCandidates: [
      'stat_highlight',
      'big_stat_with_body',
      'quote_stat_combo',
      'split_stat_image',
    ],
    componentMix: ['header', 'body or quote', 'image_placeholder optional'],
    narrativeRole: 'Break the rhythm with a punchy proof slide.',
  },
  {
    id: 'supportive_close',
    name: 'Supportive Close',
    triggers: ['cta', 'ajak', 'hubungi', 'mulai', 'diskusi', 'bantuan'],
    useWhen: 'The final slide should invite action without feeling pushy.',
    layoutCandidates: ['header_body_cta', 'cta_centered', 'quote_focus'],
    componentMix: ['header or quote', 'body optional', 'button_cta optional'],
    narrativeRole: 'Convert attention into a safe next step.',
  },
  {
    id: 'question_hook',
    name: 'Question Hook',
    triggers: ['kenapa', 'mengapa', 'pernah', 'apakah', 'why', 'question', 'tanya'],
    useWhen: 'The opening should pull the audience in with a direct question.',
    layoutCandidates: ['cover_editorial_left', 'cover_centered', 'big_statement'],
    componentMix: ['tag', 'header', 'body optional'],
    narrativeRole: 'Create curiosity before explaining the answer.',
  },
  {
    id: 'bold_claim_hook',
    name: 'Bold Claim Hook',
    triggers: ['rahasia', 'truth', 'fakta', 'jangan', 'stop', 'ternyata', 'bukan'],
    useWhen: 'The content needs a strong contrarian or provocative opening.',
    layoutCandidates: ['big_statement', 'cover_editorial_left', 'cover_with_cta'],
    componentMix: ['tag', 'header'],
    narrativeRole: 'Stop the scroll with one memorable claim.',
  },
  {
    id: 'checklist_cover',
    name: 'Checklist Cover',
    triggers: ['panduan', 'guide', 'checklist', 'tips', 'cara', 'langkah'],
    useWhen: 'The cover should preview multiple useful takeaways.',
    layoutCandidates: ['cover_checklist', 'cover_centered'],
    componentMix: ['header', 'checklist'],
    narrativeRole: 'Promise practical value immediately.',
  },
  {
    id: 'definition_explainer',
    name: 'Definition Explainer',
    triggers: ['apa itu', 'definisi', 'meaning', 'pengertian', 'explain', 'jelaskan'],
    useWhen: 'The slide introduces a concept before going deeper.',
    layoutCandidates: ['text_centered', 'text_stack', 'quote_stat_combo'],
    componentMix: ['header', 'body or quote'],
    narrativeRole: 'Clarify the concept in plain language.',
  },
  {
    id: 'cause_effect',
    name: 'Cause and Effect',
    triggers: ['penyebab', 'akibat', 'dampak', 'karena', 'sebab', 'effect', 'impact'],
    useWhen: 'The content needs to connect a behavior to its consequence.',
    layoutCandidates: [
      'split_text_left_image_right',
      'comparison_with_header',
      'checklist_with_body',
    ],
    componentMix: ['header', 'body or checklist', 'image_placeholder optional'],
    narrativeRole: 'Make causality easy to understand.',
  },
  {
    id: 'mistake_list',
    name: 'Common Mistakes',
    triggers: ['kesalahan', 'mistake', 'salah', 'hindari', 'jangan lakukan', 'error umum'],
    useWhen: 'The audience needs to recognize avoidable mistakes.',
    layoutCandidates: ['feature_cards_with_header', 'checklist_stack', 'two_column_text'],
    componentMix: ['header', 'feature_cards or checklist'],
    narrativeRole: 'Turn pitfalls into scannable warnings.',
  },
  {
    id: 'tips_list',
    name: 'Practical Tips',
    triggers: ['tips', 'trik', 'cara cepat', 'praktis', 'hack', 'rekomendasi'],
    useWhen: 'The slide gives several practical tips that stand alone.',
    layoutCandidates: ['feature_cards_with_header', 'checklist_with_body', 'feature_cards_grid'],
    componentMix: ['header optional', 'feature_cards or checklist'],
    narrativeRole: 'Deliver fast utility without heavy explanation.',
  },
  {
    id: 'dos_donts',
    name: 'Dos and Donts',
    triggers: ['do and dont', 'dos donts', 'boleh', 'jangan', 'lakukan', 'hindari'],
    useWhen: 'The content compares good and bad behaviors.',
    layoutCandidates: ['comparison_with_header', 'comparison_columns', 'two_column_text'],
    componentMix: ['comparison or checklist'],
    narrativeRole: 'Create clear behavioral contrast.',
  },
  {
    id: 'myth_vs_fact',
    name: 'Myth vs Fact',
    triggers: ['mitos', 'fakta', 'myth', 'fact', 'salah kaprah'],
    useWhen: 'The audience likely believes something inaccurate.',
    layoutCandidates: ['comparison_with_header', 'quote_stat_combo', 'big_statement'],
    componentMix: ['comparison or quote', 'header optional'],
    narrativeRole: 'Correct misconception with a memorable reframe.',
  },
  {
    id: 'framework_cards',
    name: 'Framework Cards',
    triggers: ['framework', 'metode', 'model', 'prinsip', 'pilar', 'pillar'],
    useWhen: 'The content explains a named framework or set of principles.',
    layoutCandidates: ['feature_cards_with_header', 'feature_cards_grid', 'checklist_with_body'],
    componentMix: ['header', 'feature_cards with 3-6 items'],
    narrativeRole: 'Package ideas into reusable mental buckets.',
  },
  {
    id: 'use_case_gallery',
    name: 'Use Case Gallery',
    triggers: ['use case', 'contoh penggunaan', 'kasus', 'skenario', 'aplikasi'],
    useWhen: 'The content needs multiple examples for different situations.',
    layoutCandidates: [
      'feature_cards_with_header',
      'image_top_checklist_bottom',
      'split_checklist_image',
    ],
    componentMix: ['feature_cards or checklist', 'image_placeholder optional'],
    narrativeRole: 'Show breadth through concrete use cases.',
  },
  {
    id: 'workflow_steps',
    name: 'Workflow Steps',
    triggers: ['workflow', 'alur', 'proses', 'pipeline', 'sistem kerja', 'step by step'],
    useWhen: 'The content describes a sequence or operational flow.',
    layoutCandidates: ['numbered_steps', 'numbered_with_image', 'image_top_checklist_bottom'],
    componentMix: ['header', 'checklist ordered as steps', 'image_placeholder optional'],
    narrativeRole: 'Make a process feel executable.',
  },
  {
    id: 'decision_checklist',
    name: 'Decision Checklist',
    triggers: ['pilih', 'memilih', 'decision', 'pertimbangan', 'kriteria', 'cocok'],
    useWhen: 'The audience needs criteria to decide what to do or choose.',
    layoutCandidates: ['checklist_with_body', 'two_column_text', 'comparison_with_header'],
    componentMix: ['header', 'body optional', 'checklist or comparison'],
    narrativeRole: 'Help the audience make a confident decision.',
  },
  {
    id: 'audit_scorecard',
    name: 'Audit Scorecard',
    triggers: ['audit', 'cek', 'score', 'nilai', 'evaluasi', 'assessment'],
    useWhen: 'The content asks the audience to evaluate themselves or a process.',
    layoutCandidates: ['feature_cards_with_header', 'checklist_stack', 'big_stat_with_body'],
    componentMix: ['header', 'feature_cards or checklist'],
    narrativeRole: 'Turn advice into a self-diagnostic moment.',
  },
  {
    id: 'benefit_cards',
    name: 'Benefit Cards',
    triggers: ['benefit', 'manfaat', 'keuntungan', 'value', 'nilai', 'hasil'],
    useWhen: 'The content lists benefits or reasons to care.',
    layoutCandidates: ['feature_cards_with_header', 'feature_cards_grid', 'checklist_with_body'],
    componentMix: ['header optional', 'feature_cards or checklist'],
    narrativeRole: 'Make benefits feel tangible and easy to scan.',
  },
  {
    id: 'feature_breakdown',
    name: 'Feature Breakdown',
    triggers: ['fitur', 'feature', 'fungsi', 'capability', 'tools'],
    useWhen: 'The slide explains product or service capabilities.',
    layoutCandidates: [
      'feature_cards_with_header',
      'split_header_body_cta',
      'split_checklist_image',
    ],
    componentMix: ['header', 'feature_cards or checklist', 'image_placeholder optional'],
    narrativeRole: 'Translate features into understandable value.',
  },
  {
    id: 'objection_handling',
    name: 'Objection Handling',
    triggers: ['mahal', 'ribet', 'takut', 'keberatan', 'objection', 'ragu', 'khawatir'],
    useWhen: 'The content needs to answer doubts or resistance.',
    layoutCandidates: ['comparison_with_header', 'quote_focus', 'checklist_with_body'],
    componentMix: ['comparison or quote or checklist'],
    narrativeRole: 'Reduce friction by answering the audience’s hidden objections.',
  },
  {
    id: 'social_proof',
    name: 'Social Proof',
    triggers: ['testimoni', 'testimonial', 'review', 'bukti sosial', 'dipercaya', 'customer'],
    useWhen: 'The content needs trust through a quote or customer evidence.',
    layoutCandidates: ['quote_focus', 'quote_with_image', 'quote_stat_combo'],
    componentMix: ['quote', 'image_placeholder optional', 'body optional'],
    narrativeRole: 'Use voice-of-customer or proof to increase trust.',
  },
  {
    id: 'case_study_snapshot',
    name: 'Case Study Snapshot',
    triggers: ['case study', 'studi kasus', 'hasil klien', 'before after', 'success story'],
    useWhen: 'The story needs a compact example of transformation.',
    layoutCandidates: ['split_stat_image', 'big_stat_with_body', 'comparison_with_header'],
    componentMix: ['header', 'body or comparison', 'image_placeholder optional'],
    narrativeRole: 'Compress a success story into one slide.',
  },
  {
    id: 'metric_punch',
    name: 'Metric Punch',
    triggers: ['%', 'persen', 'x lipat', 'angka', 'metric', 'stat', 'data'],
    useWhen: 'A single number should become the visual anchor.',
    layoutCandidates: ['stat_highlight', 'big_stat_with_body', 'split_stat_image'],
    componentMix: ['header', 'body', 'image_placeholder optional'],
    narrativeRole: 'Give the deck a memorable quantitative beat.',
  },
  {
    id: 'quote_reframe',
    name: 'Quote Reframe',
    triggers: ['quote', 'kutipan', 'kalimat', 'prinsip', 'mindset'],
    useWhen: 'A sentence or principle should carry the emotional shift.',
    layoutCandidates: ['quote_focus', 'quote_stat_combo', 'quote_with_image'],
    componentMix: ['quote', 'image_placeholder optional'],
    narrativeRole: 'Make the audience pause and rethink.',
  },
  {
    id: 'visual_caption',
    name: 'Visual Caption',
    triggers: ['caption', 'gambar utama', 'visual utama', 'hero image', 'full image'],
    useWhen: 'The visual should dominate and copy should be minimal.',
    layoutCandidates: ['image_full_caption', 'cover_image_full', 'image_top_text_bottom'],
    componentMix: ['image_placeholder', 'body or header'],
    narrativeRole: 'Let one image carry the idea.',
  },
  {
    id: 'visual_led_checklist',
    name: 'Visual-led Checklist',
    triggers: ['visual checklist', 'gambar dan poin', 'ilustrasi dan tips', 'image checklist'],
    useWhen: 'An image introduces several supporting points.',
    layoutCandidates: [
      'image_top_checklist_bottom',
      'split_image_checklist',
      'split_checklist_image',
    ],
    componentMix: ['image_placeholder', 'checklist', 'header optional'],
    narrativeRole: 'Pair visual attention with practical takeaways.',
  },
  {
    id: 'product_visual_cta',
    name: 'Product Visual CTA',
    triggers: ['demo', 'trial', 'coba', 'signup', 'book demo', 'produk'],
    useWhen: 'The CTA should be supported by a product or proof visual.',
    layoutCandidates: ['split_header_body_cta', 'header_body_cta', 'cta_centered'],
    componentMix: ['header', 'body', 'button_cta', 'image_placeholder optional'],
    narrativeRole: 'Bridge education into action.',
  },
  {
    id: 'negative_positive_split',
    name: 'Negative Positive Split',
    triggers: ['negatif', 'positif', 'buruk', 'baik', 'wrong right', 'salah benar'],
    useWhen: 'The content contrasts harmful and healthy patterns.',
    layoutCandidates: ['comparison_with_header', 'comparison_columns', 'two_column_text'],
    componentMix: ['comparison with positive and negative columns'],
    narrativeRole: 'Make the right behavior obvious.',
  },
  {
    id: 'timeline_like_steps',
    name: 'Timeline-like Steps',
    triggers: ['timeline', 'fase', 'phase', 'tahap', 'minggu', 'hari ke'],
    useWhen: 'The content has phases over time; rendered as numbered steps in current system.',
    layoutCandidates: ['numbered_steps', 'numbered_with_image', 'checklist_with_body'],
    componentMix: ['header', 'checklist as chronological phases'],
    narrativeRole: 'Represent progress across time without a custom timeline renderer.',
  },
  {
    id: 'problem_stack',
    name: 'Problem Stack',
    triggers: ['masalah utama', 'akar masalah', 'problem stack', 'kenapa gagal'],
    useWhen: 'Several causes compound into one bigger problem.',
    layoutCandidates: ['feature_cards_with_header', 'checklist_with_body', 'split_checklist_image'],
    componentMix: ['header', 'feature_cards or checklist', 'image_placeholder optional'],
    narrativeRole: 'Show how problems pile up.',
  },
  {
    id: 'solution_stack',
    name: 'Solution Stack',
    triggers: ['solusi', 'stack', 'toolkit', 'rekomendasi', 'kombinasi'],
    useWhen: 'The slide presents multiple solution ingredients.',
    layoutCandidates: ['feature_cards_with_header', 'checklist_with_body', 'numbered_steps'],
    componentMix: ['header', 'feature_cards or checklist'],
    narrativeRole: 'Make the recommended solution feel complete.',
  },
  {
    id: 'empathy_moment',
    name: 'Empathy Moment',
    triggers: ['takut', 'cemas', 'capek', 'frustrasi', 'khawatir', 'emosional', 'keluarga'],
    useWhen: 'The topic needs emotional validation before advice.',
    layoutCandidates: ['quote_focus', 'text_centered', 'quote_with_image'],
    componentMix: ['quote or header', 'body optional', 'image_placeholder optional'],
    narrativeRole: 'Make the audience feel understood.',
  },
  {
    id: 'authority_explainer',
    name: 'Authority Explainer',
    triggers: ['expert', 'ahli', 'riset', 'penelitian', 'menurut', 'study'],
    useWhen: 'The slide should sound evidence-informed without being too dense.',
    layoutCandidates: ['quote_stat_combo', 'stat_highlight', 'text_stack'],
    componentMix: ['quote or header', 'body'],
    narrativeRole: 'Add credibility and calm authority.',
  },
  {
    id: 'micro_story',
    name: 'Micro Story',
    triggers: ['cerita', 'story', 'kisah', 'skenario', 'bayangkan'],
    useWhen: 'The content benefits from a short relatable scenario.',
    layoutCandidates: ['text_stack', 'split_image_left_text_right', 'quote_with_image'],
    componentMix: ['header', 'body or quote', 'image_placeholder optional'],
    narrativeRole: 'Humanize the message through a tiny scene.',
  },
  {
    id: 'scenario_cards',
    name: 'Scenario Cards',
    triggers: ['skenario', 'situasi', 'contoh kasus', 'when to use', 'kapan'],
    useWhen: 'Multiple scenarios or contexts need equal weight.',
    layoutCandidates: ['feature_cards_with_header', 'feature_cards_grid'],
    componentMix: ['feature_cards with scenario labels'],
    narrativeRole: 'Show applicability across situations.',
  },
  {
    id: 'risk_matrix_simple',
    name: 'Simple Risk Matrix',
    triggers: ['risiko', 'prioritas', 'urgent', 'penting', 'matrix', 'matriks'],
    useWhen: 'The slide needs prioritization but no custom matrix renderer exists.',
    layoutCandidates: ['comparison_with_header', 'feature_cards_with_header', 'two_column_text'],
    componentMix: ['comparison or feature_cards grouped by priority'],
    narrativeRole: 'Help the audience triage what matters most.',
  },
  {
    id: 'resource_list',
    name: 'Resource List',
    triggers: ['resource', 'referensi', 'tools', 'template', 'alat bantu', 'sumber'],
    useWhen: 'The content lists helpful tools, resources, or templates.',
    layoutCandidates: ['feature_cards_with_header', 'checklist_stack', 'two_column_text'],
    componentMix: ['feature_cards or checklist'],
    narrativeRole: 'Give the audience practical resources to use.',
  },
  {
    id: 'faq_objection',
    name: 'FAQ Objection',
    triggers: ['faq', 'pertanyaan', 'sering ditanya', 'q&a', 'jawaban'],
    useWhen: 'The slide answers common questions in compact form.',
    layoutCandidates: ['feature_cards_with_header', 'checklist_with_body', 'two_column_text'],
    componentMix: ['feature_cards or checklist as Q/A pairs'],
    narrativeRole: 'Resolve confusion quickly.',
  },
  {
    id: 'launch_announcement',
    name: 'Launch Announcement',
    triggers: ['launch', 'rilis', 'baru', 'announcement', 'pengumuman', 'introducing'],
    useWhen: 'The deck announces a new product, feature, or event.',
    layoutCandidates: ['cover_with_cta', 'split_header_body_cta', 'feature_cards_with_header'],
    componentMix: ['header', 'body', 'button_cta', 'feature_cards optional'],
    narrativeRole: 'Create momentum around something new.',
  },
  {
    id: 'event_invitation',
    name: 'Event Invitation',
    triggers: ['event', 'webinar', 'workshop', 'seminar', 'daftar', 'join'],
    useWhen: 'The content invites people to attend or register.',
    layoutCandidates: ['cover_with_cta', 'header_body_cta', 'feature_cards_with_header'],
    componentMix: ['header', 'body', 'button_cta', 'feature_cards optional'],
    narrativeRole: 'Turn event details into a clear invitation.',
  },
  {
    id: 'step_visual_demo',
    name: 'Step Visual Demo',
    triggers: ['tutorial', 'demo', 'how to', 'cara pakai', 'walkthrough'],
    useWhen: 'A visual walkthrough would help explain steps.',
    layoutCandidates: [
      'numbered_with_image',
      'image_top_checklist_bottom',
      'split_image_checklist',
    ],
    componentMix: ['image_placeholder', 'checklist', 'header optional'],
    narrativeRole: 'Make instructions feel easy to follow.',
  },
  {
    id: 'comparison_proof',
    name: 'Comparison Proof',
    triggers: ['bandingkan', 'compare', 'vs', 'versus', 'lebih baik', 'alternatif'],
    useWhen: 'The audience needs to compare options or approaches.',
    layoutCandidates: ['comparison_with_header', 'comparison_columns', 'split_image_checklist'],
    componentMix: ['comparison', 'image_placeholder optional'],
    narrativeRole: 'Make tradeoffs easy to see.',
  },
  {
    id: 'aspiration_future',
    name: 'Aspirational Future',
    triggers: ['masa depan', 'future', 'bayangkan', 'goal', 'impian', 'visi'],
    useWhen: 'The slide sells a better future state.',
    layoutCandidates: ['cover_image_full', 'text_centered', 'split_image_left_text_right'],
    componentMix: ['header', 'body optional', 'image_placeholder optional'],
    narrativeRole: 'Help the audience picture the desired outcome.',
  },
  {
    id: 'pain_to_relief',
    name: 'Pain to Relief',
    triggers: ['capek', 'stress', 'frustrasi', 'relief', 'lega', 'terbebani'],
    useWhen: 'The deck moves from pain to emotional relief.',
    layoutCandidates: ['comparison_with_header', 'quote_focus', 'split_image_left_text_right'],
    componentMix: ['comparison or quote', 'image_placeholder optional'],
    narrativeRole: 'Show the emotional payoff of change.',
  },
  {
    id: 'premium_offer',
    name: 'Premium Offer',
    triggers: ['premium', 'exclusive', 'high ticket', 'mewah', 'limited', 'eksklusif'],
    useWhen: 'The content positions a high-value offer.',
    layoutCandidates: ['cover_editorial_left', 'image_full_caption', 'header_body_cta'],
    componentMix: ['header', 'body or image_placeholder', 'button_cta optional'],
    narrativeRole: 'Create desirability through restraint and clarity.',
  },
  {
    id: 'community_belonging',
    name: 'Community Belonging',
    triggers: ['komunitas', 'community', 'bersama', 'member', 'kelompok', 'support group'],
    useWhen: 'The message is about belonging, support, or shared identity.',
    layoutCandidates: ['quote_with_image', 'feature_cards_with_header', 'text_centered'],
    componentMix: ['quote or header', 'feature_cards optional', 'image_placeholder optional'],
    narrativeRole: 'Make the audience feel part of something.',
  },
  {
    id: 'safety_boundaries',
    name: 'Safety Boundaries',
    triggers: ['batasan', 'boundaries', 'aman', 'safety', 'proteksi', 'perlindungan'],
    useWhen: 'The content teaches healthy boundaries or safe practices.',
    layoutCandidates: ['checklist_with_body', 'numbered_steps', 'feature_cards_with_header'],
    componentMix: ['header', 'body optional', 'checklist or feature_cards'],
    narrativeRole: 'Translate safety into clear rules.',
  },
  {
    id: 'habit_builder',
    name: 'Habit Builder',
    triggers: ['habit', 'kebiasaan', 'rutinitas', 'daily', 'konsisten', 'disiplin'],
    useWhen: 'The slide helps the audience build or replace a habit.',
    layoutCandidates: ['numbered_steps', 'checklist_with_body', 'feature_cards_with_header'],
    componentMix: ['header', 'checklist or feature_cards'],
    narrativeRole: 'Make behavioral change feel manageable.',
  },
  {
    id: 'red_flags',
    name: 'Red Flags',
    triggers: ['red flag', 'red flags', 'tanda bahaya', 'warning sign', 'waspada'],
    useWhen: 'The content highlights warning signs.',
    layoutCandidates: ['feature_cards_with_header', 'checklist_stack', 'split_checklist_image'],
    componentMix: ['header', 'feature_cards or checklist', 'image_placeholder optional'],
    narrativeRole: 'Make risks instantly recognizable.',
  },
  {
    id: 'green_flags',
    name: 'Green Flags',
    triggers: ['green flag', 'tanda sehat', 'healthy sign', 'baik', 'positif'],
    useWhen: 'The content highlights positive signs or healthy behaviors.',
    layoutCandidates: [
      'feature_cards_with_header',
      'checklist_with_body',
      'comparison_with_header',
    ],
    componentMix: ['header', 'feature_cards or checklist'],
    narrativeRole: 'Show what good looks like.',
  },
  {
    id: 'mini_playbook',
    name: 'Mini Playbook',
    triggers: ['playbook', 'protocol', 'sop', 'template langkah', 'action plan'],
    useWhen: 'The user wants a compact action plan.',
    layoutCandidates: ['numbered_steps', 'checklist_with_body', 'header_body_cta'],
    componentMix: ['header', 'checklist', 'button_cta optional'],
    narrativeRole: 'Give a concrete plan the audience can follow today.',
  },
  {
    id: 'tool_stack',
    name: 'Tool Stack',
    triggers: ['tool stack', 'tools', 'alat', 'software', 'aplikasi', 'stack'],
    useWhen: 'The content recommends several tools or systems.',
    layoutCandidates: ['feature_cards_with_header', 'feature_cards_grid', 'split_header_body_cta'],
    componentMix: ['feature_cards', 'image_placeholder optional'],
    narrativeRole: 'Organize tools by use case or workflow role.',
  },
  {
    id: 'content_calendar',
    name: 'Content Calendar',
    triggers: ['content calendar', 'kalender konten', 'jadwal', 'posting', 'mingguan'],
    useWhen: 'The topic is a schedule or recurring plan.',
    layoutCandidates: ['numbered_steps', 'feature_cards_with_header', 'checklist_with_body'],
    componentMix: ['header', 'checklist or feature_cards as time blocks'],
    narrativeRole: 'Make planning cadence visible.',
  },
  {
    id: 'persona_segments',
    name: 'Persona Segments',
    triggers: ['persona', 'audience', 'segmen', 'target market', 'customer type'],
    useWhen: 'The content explains different audience or customer types.',
    layoutCandidates: ['feature_cards_with_header', 'comparison_with_header', 'feature_cards_grid'],
    componentMix: ['feature_cards or comparison'],
    narrativeRole: 'Differentiate audience needs clearly.',
  },
  {
    id: 'value_ladder',
    name: 'Value Ladder',
    triggers: ['value ladder', 'tier', 'paket', 'level', 'upgrade', 'pricing'],
    useWhen: 'The content explains levels of offer, maturity, or progression.',
    layoutCandidates: ['numbered_steps', 'comparison_with_header', 'feature_cards_with_header'],
    componentMix: ['checklist or comparison or feature_cards'],
    narrativeRole: 'Show progression from basic to advanced.',
  },
  {
    id: 'quick_wins',
    name: 'Quick Wins',
    triggers: ['quick win', 'cepat', 'langsung', 'hari ini', 'mudah dilakukan'],
    useWhen: 'The content should feel immediately actionable.',
    layoutCandidates: ['feature_cards_with_header', 'checklist_stack', 'numbered_steps'],
    componentMix: ['feature_cards or checklist'],
    narrativeRole: 'Give immediate momentum.',
  },
  {
    id: 'deep_dive',
    name: 'Deep Dive',
    triggers: ['deep dive', 'mendalam', 'detail', 'analisis', 'komprehensif'],
    useWhen: 'The content needs depth but must remain carousel-friendly.',
    layoutCandidates: ['text_stack', 'checklist_with_body', 'feature_cards_with_header'],
    componentMix: ['header', 'body', 'checklist or feature_cards'],
    narrativeRole: 'Compress deeper explanation without overwhelming the slide.',
  },
  {
    id: 'recap_summary',
    name: 'Recap Summary',
    triggers: ['recap', 'summary', 'ringkasan', 'kesimpulan', 'takeaway'],
    useWhen: 'The final or middle slide summarizes key takeaways.',
    layoutCandidates: ['checklist_with_body', 'feature_cards_grid', 'big_statement'],
    componentMix: ['header optional', 'checklist or feature_cards'],
    narrativeRole: 'Lock the message into memory.',
  },
  {
    id: 'bridge_to_next',
    name: 'Bridge to Next Step',
    triggers: ['next step', 'langkah berikutnya', 'lanjut', 'mulai dari', 'action'],
    useWhen: 'The deck needs a transition from learning to doing.',
    layoutCandidates: ['header_body_cta', 'numbered_steps', 'cta_centered'],
    componentMix: ['header', 'body or checklist', 'button_cta optional'],
    narrativeRole: 'Turn insight into the next action.',
  },
  {
    id: 'single_big_takeaway',
    name: 'Single Big Takeaway',
    triggers: ['intinya', 'takeaway', 'satu hal', 'poin utama', 'remember'],
    useWhen: 'One idea should dominate the slide.',
    layoutCandidates: ['big_statement', 'text_centered', 'quote_focus'],
    componentMix: ['header or quote', 'body optional'],
    narrativeRole: 'Make one message impossible to miss.',
  },
  {
    id: 'visual_metaphor_quote',
    name: 'Visual Metaphor Quote',
    triggers: ['metafora', 'quote visual', 'simbol', 'emosional', 'reflection'],
    useWhen: 'The deck needs an emotional visual pause.',
    layoutCandidates: ['quote_with_image', 'quote_focus', 'image_full_caption'],
    componentMix: ['quote or body', 'image_placeholder optional'],
    narrativeRole: 'Blend emotion, metaphor, and memory.',
  },
  {
    id: 'feature_to_benefit',
    name: 'Feature to Benefit',
    triggers: ['fitur menjadi manfaat', 'feature benefit', 'artinya untuk kamu', 'so what'],
    useWhen: 'The content must translate product details into audience value.',
    layoutCandidates: [
      'comparison_with_header',
      'feature_cards_with_header',
      'split_header_body_cta',
    ],
    componentMix: ['comparison or feature_cards', 'image_placeholder optional'],
    narrativeRole: 'Connect what it does to why it matters.',
  },
  {
    id: 'anti_pattern',
    name: 'Anti-pattern',
    triggers: ['anti pattern', 'jangan begini', 'cara salah', 'bad practice', 'keliru'],
    useWhen: 'The slide teaches by showing what not to do.',
    layoutCandidates: ['comparison_with_header', 'checklist_stack', 'big_statement'],
    componentMix: ['comparison or checklist or header'],
    narrativeRole: 'Make bad practice recognizable and avoidable.',
  },
  {
    id: 'maturity_model',
    name: 'Maturity Model',
    triggers: ['maturity', 'level', 'tahapan', 'pemula', 'advanced', 'skala'],
    useWhen: 'The topic has levels of sophistication or maturity.',
    layoutCandidates: ['numbered_steps', 'feature_cards_with_header', 'comparison_with_header'],
    componentMix: ['checklist or feature_cards or comparison'],
    narrativeRole: 'Help the audience locate their current stage.',
  },
  {
    id: 'market_insight',
    name: 'Market Insight',
    triggers: ['market', 'tren', 'trend', 'insight', 'industri', 'consumer behavior'],
    useWhen: 'The slide explains a market shift or audience behavior.',
    layoutCandidates: ['stat_highlight', 'quote_stat_combo', 'text_stack'],
    componentMix: ['header', 'body or quote'],
    narrativeRole: 'Make external change feel relevant to the audience.',
  },
  {
    id: 'brand_story',
    name: 'Brand Story',
    triggers: ['brand story', 'cerita brand', 'misi', 'visi', 'why we exist'],
    useWhen: 'The content tells why a brand or product exists.',
    layoutCandidates: ['cover_editorial_left', 'text_stack', 'quote_with_image'],
    componentMix: ['header', 'body or quote', 'image_placeholder optional'],
    narrativeRole: 'Build meaning beyond features.',
  },
  {
    id: 'testimonial_breakdown',
    name: 'Testimonial Breakdown',
    triggers: ['testimonial breakdown', 'review pelanggan', 'customer said', 'kata pelanggan'],
    useWhen: 'A customer quote needs to be unpacked into takeaways.',
    layoutCandidates: ['quote_focus', 'quote_stat_combo', 'feature_cards_with_header'],
    componentMix: ['quote', 'feature_cards optional'],
    narrativeRole: 'Turn social proof into lessons.',
  },
  {
    id: 'offer_stack',
    name: 'Offer Stack',
    triggers: ['offer', 'penawaran', 'bonus', 'paket', 'bundle', 'included'],
    useWhen: 'The slide lists what is included in an offer.',
    layoutCandidates: ['feature_cards_with_header', 'checklist_with_body', 'header_body_cta'],
    componentMix: ['feature_cards or checklist', 'button_cta optional'],
    narrativeRole: 'Make an offer feel concrete and valuable.',
  },
  {
    id: 'local_business_story',
    name: 'Local Business Story',
    triggers: ['umkm', 'bisnis kecil', 'toko lokal', 'local business', 'owner bisnis'],
    useWhen: 'The content speaks to small/local business owners.',
    layoutCandidates: [
      'split_image_left_text_right',
      'feature_cards_with_header',
      'comparison_with_header',
    ],
    componentMix: ['header', 'body or feature_cards or comparison', 'image_placeholder optional'],
    narrativeRole: 'Ground advice in everyday business reality.',
  },
  {
    id: 'family_sensitive_guidance',
    name: 'Family Sensitive Guidance',
    triggers: ['keluarga', 'rumah tangga', 'pasangan', 'anak', 'parenting'],
    useWhen: 'The topic touches family relationships and needs a calm tone.',
    layoutCandidates: ['quote_focus', 'checklist_with_body', 'split_image_left_text_right'],
    componentMix: ['quote or header', 'body or checklist', 'image_placeholder optional'],
    narrativeRole: 'Keep advice empathetic, practical, and non-sensational.',
  },
  {
    id: 'dual_image_comparison',
    name: 'Dual Image Comparison',
    triggers: [
      'before',
      'after',
      'before after',
      'before/after',
      'sebelum',
      'sesudah',
      'sebelum sesudah',
      'dulu sekarang',
      'comparison',
      'compare visual',
      'perbandingan visual',
    ],
    useWhen: 'Two visual states need to be compared directly.',
    layoutCandidates: [
      'dual_image_comparison',
      'problem_solution_visual_pair',
      'dos_donts_visual_pair',
    ],
    componentMix: ['header', '2 image_placeholder', 'body optional'],
    narrativeRole: 'Make contrast immediately visible.',
  },
  {
    id: 'product_angle_pair',
    name: 'Product Angle Pair',
    triggers: [
      'angle produk',
      'product angle',
      'close up',
      'close-up',
      'detail produk',
      'packaging',
      'kemasan',
    ],
    useWhen: 'A product needs more than one angle or detail shot.',
    layoutCandidates: ['product_angle_pair', 'collection_showcase', 'variant_selector_showcase'],
    componentMix: ['header', '2 image_placeholder', 'body optional'],
    narrativeRole: 'Show both the product and its detail/value cue.',
  },
  {
    id: 'use_case_gallery_2up',
    name: 'Use Case Gallery 2-Up',
    triggers: [
      'use case',
      'skenario',
      'penggunaan',
      'dua situasi',
      '2 use case',
      'audience segment',
    ],
    useWhen: 'Two usage scenarios or audience contexts should be shown together.',
    layoutCandidates: ['use_case_gallery_2up', 'feature_visual_cards', 'mini_gallery_3up'],
    componentMix: ['header', '2 image_placeholder', 'body optional'],
    narrativeRole: 'Translate abstract value into concrete scenes.',
  },
  {
    id: 'mini_gallery_3up',
    name: 'Mini Gallery 3-Up',
    triggers: ['tiga contoh', '3 contoh', 'contoh visual', 'variasi visual', 'gallery', 'galeri'],
    useWhen: 'Three examples, styles, or options should be previewed quickly.',
    layoutCandidates: ['mini_gallery_3up', 'case_study_snapshot_grid', 'app_screen_flow'],
    componentMix: ['header', '3 image_placeholder', 'body optional'],
    narrativeRole: 'Create variety and proof through multiple examples.',
  },
  {
    id: 'moodboard_grid',
    name: 'Moodboard Grid',
    triggers: [
      'moodboard',
      'mood board',
      'visual direction',
      'arah visual',
      'brand mood',
      'vibe',
      'aesthetic',
    ],
    useWhen: 'The slide needs to communicate an aesthetic direction.',
    layoutCandidates: ['moodboard_grid', 'outfit_or_style_board', 'event_moment_grid'],
    componentMix: ['header', '4 image_placeholder', 'body optional'],
    narrativeRole: 'Show visual atmosphere instead of explaining it.',
  },
  {
    id: 'step_visual_sequence',
    name: 'Step Visual Sequence',
    triggers: [
      'step visual',
      'langkah visual',
      'tutorial',
      'proses',
      'sequence',
      'alur',
      'onboarding',
    ],
    useWhen: 'A process is clearer when each step has a small visual.',
    layoutCandidates: ['step_visual_sequence', 'app_screen_flow', 'numbered_with_image'],
    componentMix: ['header', 'checklist', '3 image_placeholder'],
    narrativeRole: 'Turn instructions into a visual sequence.',
  },
  {
    id: 'problem_solution_visual_pair',
    name: 'Problem Solution Visual Pair',
    triggers: [
      'problem solution',
      'masalah solusi',
      'problem/solution',
      'pain solution',
      'solusi visual',
    ],
    useWhen: 'A problem state and solution state should be seen side by side.',
    layoutCandidates: [
      'problem_solution_visual_pair',
      'dual_image_comparison',
      'comparison_with_header',
    ],
    componentMix: ['header', '2 image_placeholder', 'body optional'],
    narrativeRole: 'Make the improvement concrete.',
  },
  {
    id: 'feature_visual_cards',
    name: 'Feature Visual Cards',
    triggers: ['fitur visual', 'feature visual', 'kartu fitur', 'visual cards', 'benefit visual'],
    useWhen: 'Multiple features each deserve a small visual tile.',
    layoutCandidates: ['feature_visual_cards', 'feature_cards_with_header', 'collection_showcase'],
    componentMix: ['header optional', 'feature_cards', '2-4 image_placeholder'],
    narrativeRole: 'Make feature lists feel tangible.',
  },
  {
    id: 'testimonial_portrait_product',
    name: 'Testimonial With Portrait And Product',
    triggers: [
      'testimonial',
      'review',
      'customer story',
      'portrait customer',
      'hasil pelanggan',
      'social proof',
    ],
    useWhen: 'Social proof needs both human context and product/result imagery.',
    layoutCandidates: [
      'testimonial_with_portrait_and_product',
      'social_proof_wall',
      'quote_with_image',
    ],
    componentMix: ['quote', '2 image_placeholder', 'body optional'],
    narrativeRole: 'Make proof feel credible and human.',
  },
  {
    id: 'case_study_snapshot_grid',
    name: 'Case Study Snapshot Grid',
    triggers: [
      'case study',
      'studi kasus',
      'portfolio',
      'portofolio',
      'campaign recap',
      'before process after',
    ],
    useWhen: 'A case study needs snapshots of before, process, and result.',
    layoutCandidates: ['case_study_snapshot_grid', 'mini_gallery_3up', 'social_proof_wall'],
    componentMix: ['header', '3 image_placeholder', 'body optional'],
    narrativeRole: 'Compress proof into a visual story.',
  },
  {
    id: 'dos_donts_visual_pair',
    name: 'Dos And Donts Visual Pair',
    triggers: [
      'do dont',
      'do/dont',
      'dos donts',
      'yang benar salah',
      'benar salah',
      'hindari lakukan',
    ],
    useWhen: 'Correct vs incorrect behavior or setup needs visual clarity.',
    layoutCandidates: ['dos_donts_visual_pair', 'comparison_with_header', 'dual_image_comparison'],
    componentMix: ['header', '2 image_placeholder', 'body optional'],
    narrativeRole: 'Teach by visual contrast.',
  },
  {
    id: 'outfit_style_board',
    name: 'Outfit Or Style Board',
    triggers: ['outfit', 'fashion', 'beauty', 'style board', 'lookbook', 'aksesori', 'styling'],
    useWhen: 'Fashion, beauty, or styling content needs a look plus supporting details.',
    layoutCandidates: ['outfit_or_style_board', 'moodboard_grid', 'collection_showcase'],
    componentMix: ['header', '4 image_placeholder', 'body optional'],
    narrativeRole: 'Show a complete style language.',
  },
  {
    id: 'menu_food_combo',
    name: 'Menu Or Food Combo',
    triggers: ['menu', 'food', 'makanan', 'minuman', 'combo', 'dish', 'kuliner', 'restoran'],
    useWhen: 'Food content needs hero dish plus side/drink/detail imagery.',
    layoutCandidates: ['menu_or_food_combo', 'collection_showcase', 'mini_gallery_3up'],
    componentMix: ['header', '3-4 image_placeholder', 'body optional'],
    narrativeRole: 'Make offer variety appetizing.',
  },
  {
    id: 'real_estate_room_pair',
    name: 'Real Estate Room Pair',
    triggers: [
      'real estate',
      'property',
      'properti',
      'rumah',
      'interior',
      'eksterior',
      'room pair',
    ],
    useWhen: 'Property or interior content needs two spaces shown together.',
    layoutCandidates: ['real_estate_room_pair', 'moodboard_grid', 'dual_image_comparison'],
    componentMix: ['header', '2 image_placeholder', 'body optional'],
    narrativeRole: 'Help viewers compare spaces quickly.',
  },
  {
    id: 'app_screen_flow',
    name: 'App Screen Flow',
    triggers: [
      'app flow',
      'screen flow',
      'screenshot',
      'dashboard flow',
      'ui flow',
      'saas flow',
      'onboarding screen',
    ],
    useWhen: 'A software workflow needs multiple screens in one slide.',
    layoutCandidates: ['app_screen_flow', 'mini_gallery_3up', 'feature_visual_cards'],
    componentMix: ['header', '2-3 image_placeholder', 'body optional'],
    narrativeRole: 'Explain product flow visually.',
  },
  {
    id: 'social_proof_wall',
    name: 'Social Proof Wall',
    triggers: [
      'proof wall',
      'social proof',
      'review wall',
      'ugc',
      'screenshot chat',
      'bukti hasil',
    ],
    useWhen: 'Several proof artifacts should build credibility together.',
    layoutCandidates: [
      'social_proof_wall',
      'testimonial_with_portrait_and_product',
      'case_study_snapshot_grid',
    ],
    componentMix: ['header', '3-4 image_placeholder', 'quote optional'],
    narrativeRole: 'Stack proof without overexplaining.',
  },
  {
    id: 'event_moment_grid',
    name: 'Event Moment Grid',
    triggers: ['event', 'acara', 'seminar', 'workshop', 'stage', 'speaker', 'booth', 'audience'],
    useWhen: 'Event recap needs several moments in one slide.',
    layoutCandidates: ['event_moment_grid', 'moodboard_grid', 'mini_gallery_3up'],
    componentMix: ['header', '4 image_placeholder', 'body optional'],
    narrativeRole: 'Show energy, scale, and participation.',
  },
  {
    id: 'travel_itinerary_grid',
    name: 'Travel Itinerary Grid',
    triggers: ['travel', 'itinerary', 'destinasi', 'wisata', 'hotel', 'landmark', 'liburan'],
    useWhen: 'Travel content needs destination, food, stay, and activity previews.',
    layoutCandidates: ['travel_itinerary_grid', 'moodboard_grid', 'mini_gallery_3up'],
    componentMix: ['header', '4 image_placeholder', 'body optional'],
    narrativeRole: 'Preview itinerary variety at a glance.',
  },
  {
    id: 'collection_showcase',
    name: 'Collection Showcase',
    triggers: ['collection', 'koleksi', 'catalog', 'katalog', 'bundle', 'sku', 'produk pilihan'],
    useWhen: 'Multiple products or items should appear as a collection.',
    layoutCandidates: ['collection_showcase', 'variant_selector_showcase', 'feature_visual_cards'],
    componentMix: ['header', '3-4 image_placeholder', 'body optional'],
    narrativeRole: 'Show range and choice.',
  },
  {
    id: 'variant_selector_showcase',
    name: 'Variant Selector Showcase',
    triggers: ['variant', 'varian', 'warna', 'colorway', 'ukuran', 'material', 'pilihan'],
    useWhen: 'Product variants or choices should be compared visually.',
    layoutCandidates: ['variant_selector_showcase', 'collection_showcase', 'dual_image_comparison'],
    componentMix: ['header', '3-4 image_placeholder', 'body optional'],
    narrativeRole: 'Make choices feel concrete and easy to compare.',
  },
  {
    id: 'editorial_feature_spread',
    name: 'Editorial Feature Spread',
    triggers: [
      'editorial',
      'majalah',
      'magazine',
      'feature story',
      'storytelling premium',
      'longform',
    ],
    useWhen: 'A slide should feel like a magazine feature with headline, dek, and image.',
    layoutCandidates: ['editorial_feature_spread', 'magazine_cover_story', 'article_column_layout'],
    componentMix: ['tag', 'header', 'body', 'image_placeholder'],
    narrativeRole: 'Make the content feel authored and publication-grade.',
  },
  {
    id: 'magazine_cover_story',
    name: 'Magazine Cover Story',
    triggers: ['cover story', 'magazine cover', 'cover majalah', 'hero editorial', 'issue cover'],
    useWhen: 'The opening slide needs a dramatic publication-style cover.',
    layoutCandidates: ['magazine_cover_story', 'cover_image_full', 'cover_editorial_left'],
    componentMix: ['tag', 'header', 'body optional', 'image_placeholder'],
    narrativeRole: 'Open with strong editorial presence.',
  },
  {
    id: 'pullquote_editorial',
    name: 'Pullquote Editorial',
    triggers: ['pullquote', 'pull quote', 'kutipan besar', 'quote editorial', 'key quote'],
    useWhen: 'One sentence or quote should become a rhythm break.',
    layoutCandidates: ['pullquote_editorial', 'quote_focus', 'quote_stat_combo'],
    componentMix: ['quote', 'body optional'],
    narrativeRole: 'Turn one important line into the slide anchor.',
  },
  {
    id: 'article_column_layout',
    name: 'Article Column Layout',
    triggers: ['article', 'artikel', 'essay', 'esai', 'thought leadership', 'opini panjang'],
    useWhen: 'A slide needs more narrative explanation without becoming a plain paragraph.',
    layoutCandidates: ['article_column_layout', 'text_stack', 'two_column_text'],
    componentMix: ['header', 'body'],
    narrativeRole: 'Make dense explanation feel editorial and readable.',
  },
  {
    id: 'editorial_image_caption_grid',
    name: 'Editorial Image Caption Grid',
    triggers: ['caption', 'image caption', 'caption grid', 'foto caption', 'callout editorial'],
    useWhen: 'An image needs caption-like explanation or a secondary detail image.',
    layoutCandidates: ['editorial_image_caption_grid', 'image_full_caption', 'mini_gallery_3up'],
    componentMix: ['header', 'body', '1-2 image_placeholder'],
    narrativeRole: 'Pair observation with visual evidence.',
  },
  {
    id: 'profile_story_layout',
    name: 'Profile Story Layout',
    triggers: [
      'profile',
      'profil',
      'founder story',
      'customer story',
      'expert story',
      'personal brand',
    ],
    useWhen: 'The slide tells a person-led story.',
    layoutCandidates: [
      'profile_story_layout',
      'testimonial_with_portrait_and_product',
      'quote_with_image',
    ],
    componentMix: ['header', 'body', 'image_placeholder portrait'],
    narrativeRole: 'Humanize the message through a profile frame.',
  },
  {
    id: 'reportage_photo_essay',
    name: 'Reportage Photo Essay',
    triggers: ['reportage', 'jurnalistik', 'documentary', 'photo essay', 'foto esai', 'lapangan'],
    useWhen: 'The story needs a documentary/photo-essay feel.',
    layoutCandidates: ['reportage_photo_essay', 'event_moment_grid', 'case_study_snapshot_grid'],
    componentMix: ['header', 'body optional', '3 image_placeholder'],
    narrativeRole: 'Show observed reality through multiple images.',
  },
  {
    id: 'opinion_big_statement',
    name: 'Opinion Big Statement',
    triggers: ['opinion', 'opini', 'hot take', 'contrarian', 'thesis', 'statement besar'],
    useWhen: 'A strong point of view needs a large editorial statement.',
    layoutCandidates: ['opinion_big_statement', 'big_statement', 'pullquote_editorial'],
    componentMix: ['tag', 'header', 'body optional'],
    narrativeRole: 'Frame the thesis with authority.',
  },
  {
    id: 'timeline_editorial',
    name: 'Timeline Editorial',
    triggers: ['timeline', 'chronology', 'kronologi', 'milestone', 'fase', 'phase', 'perjalanan'],
    useWhen: 'A sequence across time needs editorial pacing.',
    layoutCandidates: ['timeline_editorial', 'numbered_steps', 'step_visual_sequence'],
    componentMix: ['header', 'checklist'],
    narrativeRole: 'Turn time into a clear story arc.',
  },
  {
    id: 'data_editorial',
    name: 'Data Editorial',
    triggers: [
      'data journalism',
      'data editorial',
      'report',
      'laporan',
      'insight data',
      'angka penting',
    ],
    useWhen: 'A metric needs interpretation, not just a stat slide.',
    layoutCandidates: ['data_editorial', 'stat_highlight', 'big_stat_with_body'],
    componentMix: ['header as metric', 'body insight'],
    narrativeRole: 'Make data feel like an editorial insight.',
  },
];

export function contentIntelligenceBankStats(): {
  imageStyles: number;
  layoutRecipes: number;
  narrativeArcs: number;
} {
  return {
    imageStyles: IMAGE_STYLES.length,
    layoutRecipes: LAYOUT_RECIPES.length,
    narrativeArcs: NARRATIVE_ARCS.length,
  };
}

function scoreByTriggers(prompt: string, triggers: string[]): number {
  const lower = prompt.toLowerCase();
  return triggers.reduce((score, trigger) => {
    return lower.includes(trigger.toLowerCase()) ? score + 1 : score;
  }, 0);
}

function topByScore<T extends { triggers: string[] }>(
  items: T[],
  prompt: string,
  limit: number,
): T[] {
  return items
    .map((item, index) => ({ item, index, score: scoreByTriggers(prompt, item.triggers) }))
    .filter((entry) => entry.score > 0)
    .sort((a, b) => b.score - a.score || a.index - b.index)
    .slice(0, limit)
    .map((entry) => entry.item);
}

export function buildContentIntelligenceContext(prompt: string, slideCount: number): string {
  const arcs = topByScore(NARRATIVE_ARCS, prompt, 2);
  const styles = topByScore(IMAGE_STYLES, prompt, 3);
  const recipes = topByScore(LAYOUT_RECIPES, prompt, 12);

  const selectedArcs = arcs.length > 0 ? arcs : [NARRATIVE_ARCS[0]!];
  const selectedRecipes =
    recipes.length > 0 ? recipes : [LAYOUT_RECIPES[1]!, LAYOUT_RECIPES[2]!, LAYOUT_RECIPES[3]!];

  return JSON.stringify({
    instruction:
      'Use this bank as creative retrieval guidance. Choose and combine relevant arcs, style presets, and layout recipes. Do not output bank ids unless another schema asks for them.',
    slideCount,
    narrativeArcs: selectedArcs,
    imageStyles: styles,
    layoutRecipes: selectedRecipes,
    compositionRules: [
      'For 5+ slides, avoid header/body repetition: use at least 3 different component families when the story allows.',
      'Prefer feature_cards for multiple signs/reasons/benefits, comparison for two states, numbered_steps for protocols, quote/stat for rhythm breaks.',
      'When the user asks for a visual style, put the matched style promptFragment and avoid list into image_object_context in English.',
      'Use only layouts from the allowed layout catalog; this bank suggests candidates, not new layout ids.',
    ],
  });
}
