import type { PublicLeadSnapshot, AIUnavailableReason } from '@leads-generator/shared';
import { providerKindFromBaseUrl, requireProviderBaseUrl } from '../content/provider-key-routing.js';

export class AiProviderError extends Error {
  constructor(public readonly reason: AIUnavailableReason, message?: string) {
    super(message ?? reason);
    this.name = 'AiProviderError';
  }
}


export interface AiProviderResult {
  /** The estimated intent score from 0 to 100. */
  intentScore: number;
  /** A concise insight/explanation persisted for the lead detail UI. */
  insight: string;
  /** Lead conversion potential on the requested 1-5 star scale. */
  starRating: number;
  /** Model confidence from 0.0 to 1.0. */
  confidenceScore: number;
  /** Sales approach recommendation generated by the model. */
  recommendedAngle: string;
  /** Gemini usageMetadata token counts for this request. */
  tokenUsage: AiTokenUsage;
}

export interface AiTokenUsage {
  promptTokens: number;
  outputTokens: number;
  totalTokens: number;
}

export interface AiProvider {
  /**
   * Analyze the public snapshot and return the intent score and insight.
   * Throws an Error with a specific message ('timeout', 'provider_error',
   * 'malformed_output', 'quota_exceeded') upon failure (R13.13).
   */
  analyze(snapshot: PublicLeadSnapshot, signal?: AbortSignal): Promise<AiProviderResult>;
}

/**
 * Wrapper for the Google Generative Language API (R13.1).
 * Implements a strict 30-second timeout (R13.12).
 */
export class GeminiClient implements AiProvider {
  constructor(
    private readonly apiKey: string,
    private readonly apiBaseUrl: string = 'https://generativelanguage.googleapis.com',
    private readonly model: string = 'gemini-2.5-flash-lite'
  ) {}

  async analyze(snapshot: PublicLeadSnapshot, signal?: AbortSignal): Promise<AiProviderResult> {
    const prompt = this.buildPrompt(snapshot);
    const baseUrl = requireProviderBaseUrl(this.apiBaseUrl);
    const providerKind = providerKindFromBaseUrl(baseUrl);
    
    const url = providerKind === 'openai_compatible'
      ? `${baseUrl}/v1/chat/completions`
      : `${baseUrl}/v1beta/models/${this.model}:generateContent?key=${this.apiKey}`;
    
    // Create a 30s timeout signal (R13.12)
    const timeoutController = new AbortController();
    const timeoutId = setTimeout(() => timeoutController.abort(), 30_000);
    
    // Combine with caller's signal if present
    const combinedSignal = signal 
      ? AbortSignal.any([signal, timeoutController.signal])
      : timeoutController.signal;

    try {
      const fetchHeaders: Record<string, string> = { 'Content-Type': 'application/json' };
      if (providerKind === 'openai_compatible') {
        fetchHeaders['Authorization'] = `Bearer ${this.apiKey}`;
      }

      const fetchBody = providerKind === 'openai_compatible'
        ? {
            model: this.model,
            messages: [{ role: 'user', content: prompt }],
            response_format: { type: 'json_object' }
          }
        : {
            contents: [{ parts: [{ text: prompt }] }],
            generationConfig: {
              temperature: 0.2,
              responseMimeType: "application/json",
            }
          };

      const response = await fetch(url, {
        method: 'POST',
        headers: fetchHeaders,
        body: JSON.stringify(fetchBody),
        signal: combinedSignal,
      });

      if (!response.ok) {
        if (response.status === 429) {
          throw new AiProviderError('quota_exceeded');
        }
        const errText = typeof response.text === 'function'
          ? await response.text().catch(() => 'unknown')
          : 'unknown';
        console.error(`[GeminiClient] API Error ${response.status}: ${errText}`);
        throw new AiProviderError('provider_error');
      }

      const data: any = await response.json();
      
      try {
        let text: string | null = null;
        let tokenUsage = { promptTokens: 0, outputTokens: 0, totalTokens: 0 };

        if (providerKind === 'openai_compatible') {
          text = data?.choices?.[0]?.message?.content ?? null;
          const usage = data?.usage;
          if (usage) {
            tokenUsage = {
              promptTokens: usage.prompt_tokens ?? 0,
              outputTokens: usage.completion_tokens ?? 0,
              totalTokens: usage.total_tokens ?? 0
            };
          }
        } else {
          text = extractGeminiText(data);
          tokenUsage = extractTokenUsage(data);
        }

        if (!text) throw new Error();
        
        const parsed = JSON.parse(text) as unknown;
        if (!isLeadScoringOutput(parsed)) {
          throw new Error();
        }

        const starRating = clampInteger(parsed.star_rating, 1, 5);
        const confidenceScore = Math.max(0, Math.min(1, parsed.confidence_score ?? 0.8));
        const painPoints = normalizePainPoints(parsed.pain_points).slice(0, 4).join('; ');
        const uxFlow = normalizeInsightText(parsed.ux_analysis?.flow);
        const uxVisual = normalizeInsightText(parsed.ux_analysis?.visual);
        const performanceIssues = normalizeInsightList(parsed.performance_analysis?.issues).slice(0, 4).join('; ');
        const performanceSolutions = normalizeInsightList(parsed.performance_analysis?.solutions).slice(0, 4).join('; ');
        const insight = [
          `Rating: ${starRating} bintang`,
          `Confidence: ${Math.round(confidenceScore * 100)}%`,
          `Alasan: ${parsed.primary_reason}`,
          painPoints ? `Pain points: ${painPoints}` : null,
          uxFlow ? `UX flow: ${uxFlow}` : null,
          uxVisual ? `UX visual: ${uxVisual}` : null,
          performanceIssues ? `Performance issues: ${performanceIssues}` : null,
          performanceSolutions ? `Solusi performa: ${performanceSolutions}` : null,
          `Sales angle: ${parsed.recommended_angle}`,
        ].filter(Boolean).join(' ');
        
        return {
          intentScore: starRating * 20,
          insight: insight.substring(0, 2000),
          starRating,
          confidenceScore,
          recommendedAngle: parsed.recommended_angle.substring(0, 500),
          tokenUsage,
        };
      } catch {
        throw new AiProviderError('malformed_output'); // R13.13
      }

    } catch (e: unknown) {
      if (e instanceof AiProviderError) {
        throw e;
      }
      if (e instanceof Error) {
        if (e.name === 'AbortError' || e.name === 'TimeoutError') {
          throw new AiProviderError('timeout'); // R13.12, R13.13
        }
        if (e.message === 'quota_exceeded' || e.message === 'malformed_output' || e.message === 'provider_error') {
          throw new AiProviderError(e.message as AIUnavailableReason);
        }
      }
      throw new AiProviderError('provider_error');
    } finally {
      clearTimeout(timeoutId);
    }
  }

  private buildPrompt(snapshot: PublicLeadSnapshot): string {
    const analysisInput = toLeadScoringInput(snapshot);

    return `Anda adalah sistem AI Lead Scoring otomatis (skala 1-5 Bintang) untuk agensi produk digital (Web Design, Web App, UI/UX Revamp). Anda harus menganalisis data leads yang berasal dari berbagai sumber (Google Maps, OpenStreetMap, LinkedIn, Twitter/X, Threads).

Tugas Anda adalah menilai "Potensial Conversion Leads" menjadi output JSON bersih tanpa markdown atau teks basa-basi. Gunakan Bahasa Indonesia untuk semua value string.

### MATRIKS SEGMENTASI BISNIS (TUNING MULTI-CHANNEL):
1. PREMIUM / HIGH-TIER:
   - Maps/OSM: Klinik Utama, Law Firm, Kontraktor, Hotel, Restoran Mewah.
   - LinkedIn: Perusahaan dengan >20 karyawan, startup yang mendapat pendanaan, atau industri B2B/SaaS.
   - X/Threads: Akun bisnis/tokoh dengan >10k followers tapi tidak punya website komersial yang jelas.
2. MID-TIER: Cafe populer, Gym, Brand Lokal/E-commerce menengah, Agensi non-digital, UMKM berkembang.
3. LOW-TIER: Toko kelontong, bisnis perorangan, akun komunitas kecil, atau UMKM mikro.

### LOGIKA PENILAIAN BINTANG (1-5):
- BINTANG 5 (Hot Lead): Kategori PREMIUM/HIGH-TIER, memiliki traksi kuat (Review >20 / Followers >5k / Karyawan >10), DAN TIDAK MEMILIKI WEBSITE atau WEBSITE RUSAK (Error 404/500).
- BINTANG 4 (Warm Lead - Revamp Opportunity): Kategori PREMIUM/MID-TIER, sangat aktif di media sosial/operasional, memiliki website, TAPI websitenya lambat (>4s), tidak mobile-friendly, atau desainnya terlihat sangat jadul (Visual Disconnect).
- BINTANG 3 (Medium Potential): Kategori MID-TIER, tidak memiliki website, media sosial jarang posting, atau profil peta belum diklaim. Membutuhkan edukasi berat.
- BINTANG 2 (Low Potential): Kategori LOW-TIER atau traksi sangat rendah (Followers <500 / Review <5), tidak memiliki website. Budget kemungkinan besar tidak masuk.
- BINTANG 1 (No Prospect): Bisnis sudah memiliki website yang modern, responsif, cepat, dan terawat dengan baik di profilnya.

### PARAMETER UX & WEBSITE AUDIT:
- UX flow harus ikut dinilai: kejelasan jalur user dari landing page ke kontak/booking/checkout, kemudahan menemukan CTA, dan apakah conversion path terlihat jelas.
- UX visual harus ikut dinilai: konsistensi layout, hierarki informasi, tampilan modern vs jadul, brand trust, keterbacaan, dan mobile experience.
- Performance harus dijabarkan menjadi issue yang spesifik dan solusi yang actionable berdasarkan metrik Core Web Vitals/Lighthouse jika tersedia.
- Jika performance_audit.audit_status = "ok", WAJIB sebutkan angka metrik relevan seperti Performance Score, LCP, CLS, TBT, FCP, Speed Index, HTTPS, dan mobile viewport dalam issue/solusi. Jangan menulis "audit belum tersedia" jika metrik tersedia.
- Jika audit Lighthouse gagal, jelaskan status gagal dan sarankan fallback PageSpeed Insights/API atau audit ulang. Jangan mengarang metrik yang tidak ada.
- Jangan mengarang metrik yang tidak ada di input. Boleh memberi hipotesis berbasis data input, tetapi harus ditulis sebagai kebutuhan audit lanjutan.

### CONTOH EVALUASI MULTI-CHANNEL (FEW-SHOT):

Contoh Input (Source: LinkedIn):
{"source": "linkedin", "business_name": "Logistik Maju Bersama", "category_or_industry": "Supply Chain & Logistics", "scale_indicators": {"employee_count": 35, "followers": 1200, "review_count": 0}, "website_status": {"has_website": false, "url": "", "load_time_seconds": 0.0, "is_mobile_friendly": false}}
Contoh Output:
{"star_rating": 5, "primary_reason": "Perusahaan B2B skala menengah (35 karyawan) di LinkedIn tetapi tidak memiliki website resmi. Kebutuhan web korporat sangat tinggi dan budget memadai.", "pain_points": ["Tidak ada kredibilitas digital untuk skala perusahaan B2B"], "ux_analysis": {"flow": "Belum ada website, sehingga flow konversi dari profil publik ke inquiry bisnis belum tersedia.", "visual": "Belum ada aset visual web resmi yang bisa membangun brand trust untuk perusahaan B2B."}, "performance_analysis": {"issues": ["Tidak ada website yang bisa diaudit performanya", "Tidak ada channel web resmi untuk menangkap intent calon klien"], "solutions": ["Bangun website company profile dengan CTA inquiry yang jelas", "Tambahkan struktur halaman layanan, studi kasus, dan form kontak cepat"]}, "recommended_angle": "Hubungi decision maker di LinkedIn, tawarkan pembuatan website company profile B2B profesional."}

Contoh Input (Source: Twitter/X):
{"source": "twitter_x", "business_name": "Aroma Coffee Roasters", "category_or_industry": "Food & Beverages", "scale_indicators": {"employee_count": 0, "followers": 15400, "review_count": 0}, "website_status": {"has_website": true, "url": "https://aromacoffee.com", "load_time_seconds": 6.1, "is_mobile_friendly": false}}
Contoh Output:
{"star_rating": 4, "primary_reason": "Brand F&B populer di Twitter dengan 15k+ followers, namun website yang tertulis di bio lambat (6.1s) dan tidak ramah mobile.", "pain_points": ["Website lambat menghambat konversi dari media sosial", "Pengalaman mobile buruk untuk pelanggan kafe"], "ux_analysis": {"flow": "Traffic dari media sosial berisiko putus karena pengalaman mobile buruk sebelum user menemukan menu, lokasi, atau CTA.", "visual": "Website perlu diselaraskan dengan energi brand sosial agar tidak terjadi visual disconnect."}, "performance_analysis": {"issues": ["Load time 6.1 detik melebihi ambang 4 detik", "Website tidak mobile-friendly"], "solutions": ["Optimasi gambar, caching, dan script blocking", "Redesign layout mobile-first untuk CTA menu, lokasi, dan order"]}, "recommended_angle": "Tawarkan optimasi performa dan redesign website menjadi mobile-first untuk menangkap traffic dari media sosial mereka."}

### FORMAT OUTPUT WAJIB:
Kembalikan hanya JSON valid dengan struktur ini:
{
  "star_rating": 1,
  "primary_reason": "String alasan utama dalam Bahasa Indonesia",
  "pain_points": ["Array pain point bisnis dan digital"],
  "ux_analysis": {
    "flow": "Analisa conversion flow dan friction utama",
    "visual": "Analisa kualitas visual, trust, dan mobile experience"
  },
  "performance_analysis": {
    "issues": ["Daftar issue performa/teknis secara detail"],
    "solutions": ["Daftar solusi teknis dan UX yang actionable"]
  },
  "recommended_angle": "Pendekatan sales singkat"
}

### DATA YANG HARUS ANDA ANALISIS SEKARANG:
Analisis data di bawah ini dan kembalikan hanya dalam format JSON sesuai contoh.

${JSON.stringify(analysisInput, null, 2)}`;
  }
}

function toLeadScoringInput(snapshot: PublicLeadSnapshot) {
  const websiteUrl = snapshot.profileUrl ?? '';
  const audit = snapshot.websiteAudit;
  const lighthouse = audit?.lighthouse;

  return {
    source: normalizeSource(snapshot.source),
    business_name: snapshot.name ?? '',
    category_or_industry: snapshot.matchedKeywords.join(', '),
    scale_indicators: {
      employee_count: 0,
      followers: 0,
      review_count: 0,
    },
    website_status: {
      has_website: websiteUrl.length > 0,
      url: websiteUrl,
      final_url: audit?.finalUrl ?? websiteUrl,
      http_status: audit?.httpStatus ?? null,
      load_time_seconds: audit?.loadTimeSeconds ?? null,
      is_mobile_friendly: audit?.isMobileFriendly ?? null,
      https_enabled: audit?.httpsEnabled ?? (websiteUrl ? websiteUrl.toLowerCase().startsWith('https://') : null),
    },
    ux_audit: {
      audit_status: audit?.status ?? (websiteUrl ? 'not_run' : 'not_applicable_no_website'),
      flow_signals: audit?.uxFlowSignals ?? [],
      visual_signals: audit?.visualSignals ?? [],
      conversion_signals: audit?.signals ? {
        has_contact_link: audit.signals.hasContactLink,
        has_whatsapp: audit.signals.hasWhatsapp,
        has_email_link: audit.signals.hasEmailLink,
        has_phone_link: audit.signals.hasPhoneLink,
        has_form: audit.signals.hasForm,
        cta_labels: audit.signals.ctaLabels,
        headings: audit.signals.headings,
      } : null,
    },
    performance_audit: {
      audit_status: audit?.status ?? (websiteUrl ? 'not_run' : 'not_applicable_no_website'),
      lighthouse_scores: lighthouse ? {
        performance: lighthouse.performanceScore ?? null,
        accessibility: lighthouse.accessibilityScore ?? null,
        best_practices: lighthouse.bestPracticesScore ?? null,
        seo: lighthouse.seoScore ?? null,
      } : null,
      core_web_vitals: lighthouse ? {
        fcp_ms: lighthouse.firstContentfulPaintMs ?? null,
        lcp_ms: lighthouse.largestContentfulPaintMs ?? null,
        cls: lighthouse.cumulativeLayoutShift ?? null,
        tbt_ms: lighthouse.totalBlockingTimeMs ?? null,
        speed_index_ms: lighthouse.speedIndexMs ?? null,
        tti_ms: lighthouse.timeToInteractiveMs ?? null,
        inp_ms: lighthouse.interactionToNextPaintMs ?? null,
      } : null,
      technical_signals: audit?.signals ? {
        viewport_passed: audit.signals.hasViewport,
        image_count: audit.signals.imageCount,
        images_missing_alt: audit.signals.imagesMissingAlt,
        script_count: audit.signals.scriptCount,
        stylesheet_count: audit.signals.stylesheetCount,
      } : null,
      issue_details: audit?.issues ?? [],
      recommended_fixes: audit?.solutions ?? [],
    },
  };
}

function normalizeSource(source: string | undefined) {
  if (!source) return 'unknown';
  const normalized = source.toLowerCase();
  if (normalized.includes('google-scraper') || normalized.includes('openstreetmap')) return 'openstreetmap';
  if (normalized.includes('google') || normalized.includes('maps')) return 'google_maps';
  if (normalized.includes('linkedin')) return 'linkedin';
  if (normalized.includes('threads')) return 'threads';
  if (normalized.includes('twitter') || normalized.includes('x')) return 'twitter_x';
  if (normalized.includes('instagram')) return 'instagram';
  if (normalized.includes('facebook')) return 'facebook';
  return normalized;
}

function extractTokenUsage(value: unknown): AiTokenUsage {
  if (typeof value !== 'object' || value === null) {
    return { promptTokens: 0, outputTokens: 0, totalTokens: 0 };
  }

  const usage = (value as Record<string, unknown>).usageMetadata;
  if (typeof usage !== 'object' || usage === null) {
    return { promptTokens: 0, outputTokens: 0, totalTokens: 0 };
  }

  const metadata = usage as Record<string, unknown>;
  const promptTokens = numberField(metadata.promptTokenCount);
  const outputTokens = numberField(metadata.candidatesTokenCount);
  const totalTokens = numberField(metadata.totalTokenCount) || promptTokens + outputTokens;

  return { promptTokens, outputTokens, totalTokens };
}

function numberField(value: unknown): number {
  return typeof value === 'number' && Number.isFinite(value) ? Math.max(0, Math.floor(value)) : 0;
}

interface LeadScoringOutput {
  star_rating: number;
  confidence_score?: number;
  primary_reason: string;
  pain_points: string[];
  ux_analysis?: {
    flow?: string;
    visual?: string;
  };
  performance_analysis?: {
    issues?: string[];
    solutions?: string[];
  };
  recommended_angle: string;
}

function isLeadScoringOutput(value: unknown): value is LeadScoringOutput {
  if (typeof value !== 'object' || value === null) return false;
  const candidate = value as Record<string, unknown>;
  return (
    typeof candidate.star_rating === 'number' &&
    candidate.star_rating >= 1 &&
    candidate.star_rating <= 5 &&
    (candidate.confidence_score === undefined ||
      (typeof candidate.confidence_score === 'number' &&
        candidate.confidence_score >= 0 &&
        candidate.confidence_score <= 1)) &&
    typeof candidate.primary_reason === 'string' &&
    Array.isArray(candidate.pain_points) &&
    candidate.pain_points.every((item) => typeof item === 'string') &&
    (candidate.ux_analysis === undefined || isUxAnalysis(candidate.ux_analysis)) &&
    (candidate.performance_analysis === undefined || isPerformanceAnalysis(candidate.performance_analysis)) &&
    typeof candidate.recommended_angle === 'string'
  );
}

function clampInteger(value: number, min: number, max: number) {
  return Math.max(min, Math.min(max, Math.floor(value)));
}

function normalizePainPoints(items: string[]): string[] {
  return items
    .map((item) => item.trim())
    .filter(Boolean)
    .map((item) => {
      if (/\bunknown\b|not explicitly stated|likely unknown|tidak diketahui|belum diketahui/i.test(item)) {
        return 'Perlu audit website lanjutan untuk memastikan performa, mobile responsiveness, dan keamanan';
      }
      return item;
    })
    .filter((item, index, array) => array.indexOf(item) === index);
}

function isUxAnalysis(value: unknown): value is LeadScoringOutput['ux_analysis'] {
  if (typeof value !== 'object' || value === null) return false;
  const candidate = value as Record<string, unknown>;
  return (
    (candidate.flow === undefined || typeof candidate.flow === 'string') &&
    (candidate.visual === undefined || typeof candidate.visual === 'string')
  );
}

function isPerformanceAnalysis(value: unknown): value is LeadScoringOutput['performance_analysis'] {
  if (typeof value !== 'object' || value === null) return false;
  const candidate = value as Record<string, unknown>;
  return (
    (candidate.issues === undefined ||
      (Array.isArray(candidate.issues) && candidate.issues.every((item) => typeof item === 'string'))) &&
    (candidate.solutions === undefined ||
      (Array.isArray(candidate.solutions) && candidate.solutions.every((item) => typeof item === 'string')))
  );
}

function normalizeInsightText(value: string | undefined): string | null {
  if (!value) return null;
  const trimmed = value.trim();
  if (!trimmed || /\bunknown\b|not explicitly stated|likely unknown|tidak diketahui|belum diketahui/i.test(trimmed)) {
    return null;
  }
  return trimmed;
}

function normalizeInsightList(items: string[] | undefined): string[] {
  if (!items) return [];
  return items
    .map((item) => normalizeInsightText(item))
    .filter((item): item is string => Boolean(item))
    .filter((item, index, array) => array.indexOf(item) === index);
}

function extractGeminiText(value: unknown): string | null {
  if (typeof value !== 'object' || value === null) return null;
  const root = value as Record<string, unknown>;
  const candidates = root.candidates;
  if (!Array.isArray(candidates)) return null;
  const firstCandidate = (candidates as unknown[])[0];
  if (typeof firstCandidate !== 'object' || firstCandidate === null) return null;
  const content = (firstCandidate as Record<string, unknown>).content;
  if (typeof content !== 'object' || content === null) return null;
  const parts = (content as Record<string, unknown>).parts;
  if (!Array.isArray(parts)) return null;
  const firstPart = (parts as unknown[])[0];
  if (typeof firstPart !== 'object' || firstPart === null) return null;
  const text = (firstPart as Record<string, unknown>).text;
  return typeof text === 'string' ? text : null;
}
